# Generated by Django 4.2.24 on 2025-09-30 07:57

from django.db import migrations, models


def forwards(apps, schema_editor):
    AccountProfile = apps.get_model("accounts", "AccountProfile")
    AccountProfile.objects.filter(role="MAIN").update(role="OWNER")


def backwards(apps, schema_editor):
    AccountProfile = apps.get_model("accounts", "AccountProfile")
    AccountProfile.objects.filter(role="OWNER").update(role="MAIN")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountprofile",
            name="is_system",
        ),
        migrations.AlterField(
            model_name="accountprofile",
            name="role",
            field=models.CharField(choices=[("OWNER", "مالك"), ("MANAGER", "مدير"), ("CASHIER", "كاشير")], max_length=20),
        ),
        migrations.RunPython(forwards, backwards),
    ]
