# Generated by Django 4.2.24 on 2025-10-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_accountprofile_is_system_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountprofile',
            name='role',
            field=models.CharField(choices=[('OWNER', 'مالك'), ('MANAGER', 'مدير'), ('CASHIER', 'كاشير')], db_index=True, default='CASHIER', max_length=20),
        ),
    ]
