# Generated by Django 4.2.24 on 2025-11-13 11:43

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_customers_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer profile',
                'verbose_name_plural': 'Customer profiles',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SalesBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('pay_status', models.CharField(choices=[('full', 'Paid in full'), ('none', 'Unpaid'), ('partial', 'Partially paid')], default='full', max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('parked', models.BooleanField(default=True, help_text="If True, this bill is 'parked' (draft) and editable.")),
                ('finalized', models.BooleanField(default=False, help_text='If True, this bill was saved as final and should not be edited from POS.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_bills', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='pos.customerprofile')),
            ],
            options={
                'verbose_name': 'Sales bill (POS)',
                'verbose_name_plural': 'Sales bills (POS)',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SalesBillRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('product_number', models.CharField(blank=True, max_length=50)),
                ('qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('uom_index', models.PositiveSmallIntegerField(default=1, help_text='1 = primary unit, 2 = secondary unit')),
                ('unit_price', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Price per primary unit', max_digits=14)),
                ('disc_amount', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('disc_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='pos.salesbill')),
            ],
            options={
                'verbose_name': 'Sales bill row',
                'verbose_name_plural': 'Sales bill rows',
                'ordering': ('id',),
            },
        ),
    ]
