# Generated by Django 4.2.24 on 2025-12-09 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'POS work day',
                'verbose_name_plural': 'POS work days',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='PosLoginSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('closed_reason', models.CharField(blank=True, max_length=32)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_sessions', to='pos.posday')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_login_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'POS login session',
                'verbose_name_plural': 'POS login sessions',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='PosShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='pos.posday')),
                ('login_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='pos.posloginsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'POS shift',
                'verbose_name_plural': 'POS shifts',
                'ordering': ('-started_at',),
            },
        ),
        migrations.AddField(
            model_name='salesbill',
            name='login_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='pos.posloginsession'),
        ),
        migrations.AddField(
            model_name='salesbill',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='pos.posshift'),
        ),
        migrations.AddField(
            model_name='salesbill',
            name='work_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='pos.posday'),
        ),
    ]
