# Generated by Django 4.2.24 on 2025-12-26 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0002_posday_posloginsession_posshift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesbill',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesbill',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_bills_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesbill',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft-delete flag (only for parked bills).'),
        ),
    ]
