# Generated by Django 4.2.24 on 2026-01-12 15:50

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0012_backfill_moneycontainer_balance_syp'),
        ('pos', '0003_salesbill_deleted_at_salesbill_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesbill',
            name='fx_rate_used',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='salesbill',
            name='money_container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sales_bills', to='financials.moneycontainer'),
        ),
        migrations.AddField(
            model_name='salesbill',
            name='settlement_currency',
            field=models.CharField(blank=True, choices=[('SYP', 'SYP'), ('USD', 'USD')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='salesbill',
            name='settlement_mode',
            field=models.CharField(choices=[('split', 'Split (SYP+USD)'), ('all_syp', 'All in SYP'), ('all_usd', 'All in USD')], default='split', max_length=12),
        ),
        migrations.AddField(
            model_name='salesbill',
            name='total_syp',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14),
        ),
        migrations.AddField(
            model_name='salesbill',
            name='total_usd',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14),
        ),
        migrations.AddField(
            model_name='salesbillrow',
            name='sale_currency',
            field=models.CharField(choices=[('SYP', 'SYP'), ('USD', 'USD')], default='SYP', max_length=3),
        ),
    ]
