# Generated by Django 4.2.24 on 2026-01-16 10:28

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_salesreturn'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='salesreturn',
            new_name='pos_salesre_sale_bi_95284e_idx',
            old_name='pos_salesr_sale_bi_f9ac5e_idx',
        ),
        migrations.RenameIndex(
            model_name='salesreturn',
            new_name='pos_salesre_status_6d385d_idx',
            old_name='pos_salesr_status_8f0b6a_idx',
        ),
        migrations.RenameIndex(
            model_name='salesreturnrow',
            new_name='pos_salesre_ret_id_c16055_idx',
            old_name='pos_salesr_ret_id_4b9f4b_idx',
        ),
        migrations.RenameIndex(
            model_name='salesreturnrow',
            new_name='pos_salesre_sale_ro_79d781_idx',
            old_name='pos_salesr_sale_ro_2b6a07_idx',
        ),
        migrations.RenameIndex(
            model_name='salesreturnrow',
            new_name='pos_salesre_product_a42eb2_idx',
            old_name='pos_salesr_product_3af7a3_idx',
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='total_syp',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='total_usd',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='salesreturnrow',
            name='qty_returned',
            field=models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
