# Generated by Django 4.2.24 on 2026-04-22 10:59

from decimal import Decimal, ROUND_HALF_UP
from django.db import migrations, models


TWOPLACES = Decimal("0.01")


def _q2(value):
    if value is None:
        return None
    return Decimal(str(value)).quantize(TWOPLACES, rounding=ROUND_HALF_UP)


def _round_pos_money_fx_fields(apps, schema_editor):
    SalesBill = apps.get_model("pos", "SalesBill")
    for obj in SalesBill.objects.only("id", "fx_rate_used").iterator(chunk_size=1000):
        old = obj.fx_rate_used
        new = _q2(old)
        if new != old:
            obj.fx_rate_used = new
            obj.save(update_fields=["fx_rate_used"])

    SalesBillRow = apps.get_model("pos", "SalesBillRow")
    sbr_fields = ("unit_price", "unit_cost_at_txn", "fx_rate_at_txn")
    for obj in SalesBillRow.objects.only("id", *sbr_fields).iterator(chunk_size=1000):
        update_fields = []
        for field_name in sbr_fields:
            old = getattr(obj, field_name)
            new = _q2(old)
            if new != old:
                setattr(obj, field_name, new)
                update_fields.append(field_name)
        if update_fields:
            obj.save(update_fields=update_fields)

    SalesReturnRow = apps.get_model("pos", "SalesReturnRow")
    srr_fields = ("unit_price_at_sale", "unit_cost_at_txn", "fx_rate_at_txn")
    for obj in SalesReturnRow.objects.only("id", *srr_fields).iterator(chunk_size=1000):
        update_fields = []
        for field_name in srr_fields:
            old = getattr(obj, field_name)
            new = _q2(old)
            if new != old:
                setattr(obj, field_name, new)
                update_fields.append(field_name)
        if update_fields:
            obj.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_salesbill_public_id'),
    ]

    operations = [
        migrations.RunPython(_round_pos_money_fx_fields, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='salesbill',
            name='fx_rate_used',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesbillrow',
            name='fx_rate_at_txn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesbillrow',
            name='unit_cost_at_txn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='salesbillrow',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price per primary unit', max_digits=14),
        ),
        migrations.AlterField(
            model_name='salesreturnrow',
            name='fx_rate_at_txn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesreturnrow',
            name='unit_cost_at_txn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='salesreturnrow',
            name='unit_price_at_sale',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
    ]
