# Generated by Django 4.2.24 on 2026-04-22 12:03

from decimal import Decimal, ROUND_HALF_UP
import django.core.validators
from django.db import migrations, models


TWOPLACES = Decimal("0.01")


def _q2(value):
    if value is None:
        return None
    return Decimal(str(value)).quantize(TWOPLACES, rounding=ROUND_HALF_UP)


def _round_pos_derived_totals(apps, schema_editor):
    SalesBill = apps.get_model("pos", "SalesBill")
    sb_fields = ("total_amount", "total_syp", "total_usd")
    for obj in SalesBill.objects.only("id", *sb_fields).iterator(chunk_size=1000):
        update_fields = []
        for field_name in sb_fields:
            old = getattr(obj, field_name)
            new = _q2(old)
            if new != old:
                setattr(obj, field_name, new)
                update_fields.append(field_name)
        if update_fields:
            obj.save(update_fields=update_fields)

    SalesBillRow = apps.get_model("pos", "SalesBillRow")
    for obj in SalesBillRow.objects.only("id", "disc_amount").iterator(chunk_size=1000):
        old = obj.disc_amount
        new = _q2(old)
        if new != old:
            obj.disc_amount = new
            obj.save(update_fields=["disc_amount"])

    SalesReturn = apps.get_model("pos", "SalesReturn")
    sr_fields = ("total_syp", "total_usd")
    for obj in SalesReturn.objects.only("id", *sr_fields).iterator(chunk_size=1000):
        update_fields = []
        for field_name in sr_fields:
            old = getattr(obj, field_name)
            new = _q2(old)
            if new != old:
                setattr(obj, field_name, new)
                update_fields.append(field_name)
        if update_fields:
            obj.save(update_fields=update_fields)

    SalesReturnRow = apps.get_model("pos", "SalesReturnRow")
    srr_fields = ("discount_amount_at_txn", "line_total")
    for obj in SalesReturnRow.objects.only("id", *srr_fields).iterator(chunk_size=1000):
        update_fields = []
        for field_name in srr_fields:
            old = getattr(obj, field_name)
            new = _q2(old)
            if new != old:
                setattr(obj, field_name, new)
                update_fields.append(field_name)
        if update_fields:
            obj.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_alter_salesbill_fx_rate_used_and_more'),
    ]

    operations = [
        migrations.RunPython(_round_pos_derived_totals, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='salesbill',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='salesbill',
            name='total_syp',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='salesbill',
            name='total_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='salesbillrow',
            name='disc_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='total_syp',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='total_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='salesreturnrow',
            name='discount_amount_at_txn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='salesreturnrow',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
    ]
