# Generated by Django 4.2.24 on 2026-05-05 23:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_alter_salesbill_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesbill',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
    ]
