# Generated by Django 4.2.24 on 2025-11-21 11:55

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0008_alter_productbarcode_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('code', models.CharField(db_index=True, help_text="Short machine-readable code, e.g. 'store', 'wh1'.", max_length=32, unique=True)),
                ('is_store', models.BooleanField(default=False, help_text='Exactly one main store for POS / website.')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_primary', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Current quantity in primary unit for this product in this container.', max_digits=14)),
                ('avg_unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Average cost per primary unit in this container (optional for now).', max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='stock.productcontainer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='catalog.product')),
            ],
            options={
                'indexes': [models.Index(fields=['product', 'container'], name='stock_stock_product_ce69b2_idx'), models.Index(fields=['container'], name='stock_stock_contain_8f89fb_idx')],
                'unique_together': {('product', 'container')},
            },
        ),
    ]
