# Generated by Django 4.2.24 on 2025-11-27 12:05

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_productbarcode_unique_together_and_more'),
        ('stock', '0002_default_containers'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockFifoLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_remaining', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Remaining qty in primary unit for this FIFO layer.', max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Cost per primary unit for this FIFO layer.', max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation time (used for FIFO ordering).')),
                ('source_app', models.CharField(blank=True, default='', max_length=32)),
                ('source_model', models.CharField(blank=True, default='', max_length=64)),
                ('source_id', models.CharField(blank=True, default='', max_length=36)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fifo_layers', to='stock.productcontainer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fifo_layers', to='catalog.product')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['product', 'container', 'created_at'], name='stock_stock_product_225322_idx')],
            },
        ),
    ]
