# Generated by Django 4.2.24 on 2025-11-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stockfifolayer'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productcontainer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_store', True)), fields=('is_store',), name='unique_main_store_container'),
        ),
    ]
