# Generated by Django 4.2.24 on 2026-01-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_productcontainer_unique_main_store_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockfifolayer',
            name='cost_currency',
            field=models.CharField(choices=[('SYP', 'SYP'), ('USD', 'USD')], db_index=True, default='SYP', max_length=3),
        ),
    ]
