# Generated by Django 4.2.24 on 2026-01-11

from django.db import migrations


def forwards(apps, schema_editor):
    StockFifoLayer = apps.get_model("stock", "StockFifoLayer")
    StockFifoLayer.objects.filter(cost_currency__isnull=True).update(cost_currency="SYP")


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0005_stockfifolayer_cost_currency"),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
