# Generated by Django 4.2.24 on 2026-04-22 10:59

from decimal import Decimal, ROUND_HALF_UP
from django.db import migrations, models


TWOPLACES = Decimal("0.01")


def _q2(value):
    if value is None:
        return None
    return Decimal(str(value)).quantize(TWOPLACES, rounding=ROUND_HALF_UP)


def _round_stock_cost_fields(apps, schema_editor):
    StockEntry = apps.get_model("stock", "StockEntry")
    for obj in StockEntry.objects.only("id", "avg_unit_cost").iterator(chunk_size=1000):
        old = obj.avg_unit_cost
        new = _q2(old)
        if new != old:
            obj.avg_unit_cost = new
            obj.save(update_fields=["avg_unit_cost"])

    StockFifoLayer = apps.get_model("stock", "StockFifoLayer")
    for obj in StockFifoLayer.objects.only("id", "unit_cost").iterator(chunk_size=1000):
        old = obj.unit_cost
        new = _q2(old)
        if new != old:
            obj.unit_cost = new
            obj.save(update_fields=["unit_cost"])


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_backfill_stockfifolayer_cost_currency'),
    ]

    operations = [
        migrations.RunPython(_round_stock_cost_fields, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='stockentry',
            name='avg_unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average cost per primary unit in this container (optional for now).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockfifolayer',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost per primary unit for this FIFO layer.', max_digits=12),
        ),
    ]
