# Generated by Django 4.2.24 on 2025-10-04 09:17

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(django.db.models.functions.text.Lower('name'), name='ix_collection_name_ci')],
            },
        ),
        migrations.AddConstraint(
            model_name='productcollection',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uq_collection_name_ci', violation_error_message='اسم المجموعة موجود مسبقاً (حساسية غير مفعلة).'),
        ),
    ]
