# Generated by Django 4.2.24 on 2025-10-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcollection',
            name='code',
            field=models.CharField(max_length=8, blank=True, null=True, db_index=True),
    ),
        migrations.AddConstraint(
            model_name='productcollection',
            constraint=models.CheckConstraint(check=models.Q(('code__regex', '^#\\d{3,}$')), name='ck_collection_code_format'),
        ),
    ]
