# Generated by Django 4.2.24 on 2025-10-06 08:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productcollection_code_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productcollection',
            name='ck_collection_code_format',
        ),
        migrations.AlterField(
            model_name='productcollection',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^#\\d{3,}$', message='Code must look like #001')]),
        ),
    ]
