# Generated by Django 4.2.24 on 2025-10-06 09:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_productcollection_ck_collection_code_format_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('unit_primary', models.CharField(choices=[('g', 'غرام'), ('pc', 'قطعة'), ('L', 'ليتر')], max_length=4)),
                ('unit_secondary', models.CharField(blank=True, choices=[('g', 'غرام'), ('pc', 'قطعة'), ('L', 'ليتر')], max_length=4)),
                ('conversion_factor', models.DecimalField(blank=True, decimal_places=4, help_text='How many primary units in one secondary unit (e.g., 1000 g per 1 L).', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0.0001)])),
                ('cost', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('unit_primary_id', models.CharField(blank=True, max_length=32, unique=True)),
                ('unit_secondary_id', models.CharField(blank=True, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(blank=True, db_index=True, max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^@\\d{3,}$', 'Set code must look like @001')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sets', to='catalog.productcollection')),
            ],
            options={
                'ordering': ['collection__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_index', models.IntegerField(choices=[(1, 'الوحدة الأولى'), (2, 'الوحدة الثانية')])),
                ('barcode', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='catalog.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.productset'),
        ),
        migrations.AddIndex(
            model_name='productset',
            index=models.Index(fields=['collection'], name='catalog_pro_collect_ccf768_idx'),
        ),
        migrations.AddIndex(
            model_name='productset',
            index=models.Index(django.db.models.functions.text.Lower('name'), name='ix_set_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='productset',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('collection'), name='uq_set_name_ci_per_collection'),
        ),
        migrations.AddIndex(
            model_name='productbarcode',
            index=models.Index(fields=['product'], name='catalog_pro_product_412f8d_idx'),
        ),
        migrations.AddIndex(
            model_name='productbarcode',
            index=models.Index(fields=['unit_index'], name='catalog_pro_unit_in_f1350f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productbarcode',
            unique_together={('product', 'unit_index', 'barcode')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(django.db.models.functions.text.Lower('name'), name='ix_product_name_ci'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['set'], name='catalog_pro_set_id_428938_idx'),
        ),
    ]
