# Generated by Django 4.2.24 on 2025-10-10 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_make_unit_ids_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit_primary_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit_secondary_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_primary',
            field=models.CharField(choices=[('g', 'غرام'), ('pc', 'قطعة'), ('L', 'ليتر'), ('PKG', 'طرد'), ('BNDL', 'حزمة')], max_length=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_secondary',
            field=models.CharField(blank=True, choices=[('g', 'غرام'), ('pc', 'قطعة'), ('L', 'ليتر'), ('PKG', 'طرد'), ('BNDL', 'حزمة')], max_length=4),
        ),
        migrations.CreateModel(
            name='ProductUnitId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_index', models.IntegerField(choices=[(1, 'الوحدة الأولى'), (2, 'الوحدة الثانية')])),
                ('value', models.CharField(db_index=True, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_ids', to='catalog.product')),
            ],
            options={
                'indexes': [models.Index(fields=['product'], name='catalog_pro_product_7815b2_idx'), models.Index(fields=['unit_index'], name='catalog_pro_unit_in_98427b_idx')],
            },
        ),
    ]
