# Generated by Django 4.2.24 on 2025-10-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_product_unit_primary_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_qty',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Current stock in primary unit; may be negative.', max_digits=14),
        ),
    ]
