# Generated by Django 4.2.24 on 2025-10-21 21:49

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_stock_qty'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productbarcode',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uq_product_name_ci', violation_error_message='اسم المنتج موجود مسبقاً (بدون حساسية حالة الأحرف).'),
        ),
    ]
