# Generated by Django 4.2.24 on 2025-12-25 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0008_alter_productbarcode_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogDataJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('import', 'Import'), ('export', 'Export')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], db_index=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('summary_text', models.TextField(blank=True, default='{}')),
                ('rows_text', models.TextField(blank=True, default='[]')),
                ('meta_text', models.TextField(blank=True, default='{}')),
                ('error', models.TextField(blank=True, default='')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_data_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
