# Generated by Django 4.2.24 on 2026-01-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_catalogdatajob'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_syp',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='default_currency',
            field=models.CharField(blank=True, choices=[('SYP', 'SYP'), ('USD', 'USD')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='enable_syp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='enable_usd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='price_syp',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
