# Generated by Django 4.2.24 on 2026-01-12 09:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_product_cost_syp_product_cost_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_syp_purchasing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='allow_syp_sales',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='allow_usd_purchasing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='allow_usd_sales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='default_cost_syp',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='default_cost_usd',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='default_price_syp',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='default_price_usd',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='default_purchase_currency',
            field=models.CharField(blank=True, choices=[('SYP', 'SYP'), ('USD', 'USD')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='default_sale_currency',
            field=models.CharField(blank=True, choices=[('SYP', 'SYP'), ('USD', 'USD')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='latest_cost_syp',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='latest_cost_usd',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='latest_price_syp',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='latest_price_usd',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12),
        ),
    ]
