# Generated by Codex
from __future__ import annotations

from django.db import migrations, models
from django.db.models import Q
from django.db.models.functions import Lower


def sync_identifier_active(apps, schema_editor):
    ProductBarcode = apps.get_model("catalog", "ProductBarcode")
    ProductUnitId = apps.get_model("catalog", "ProductUnitId")

    ProductBarcode.objects.update(is_active=True)
    ProductUnitId.objects.update(is_active=True)

    ProductBarcode.objects.filter(product__is_active=False).update(is_active=False)
    ProductUnitId.objects.filter(product__is_active=False).update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_backfill_product_currency_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_number",
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=False),
        ),
        migrations.AlterField(
            model_name="productunitid",
            name="value",
            field=models.CharField(db_index=True, max_length=32, unique=False),
        ),
        migrations.AlterField(
            model_name="productbarcode",
            name="barcode",
            field=models.CharField(db_index=True, max_length=64, unique=False),
        ),
        migrations.AddField(
            model_name="productunitid",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="productbarcode",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.RunPython(sync_identifier_active, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="product",
            name="uq_product_name_ci",
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                condition=Q(is_active=True),
                fields=("product_number",),
                name="uq_product_number_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                Lower("name"),
                condition=Q(is_active=True),
                name="uq_product_name_ci_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="productunitid",
            constraint=models.UniqueConstraint(
                condition=Q(is_active=True),
                fields=("value",),
                name="uq_unit_id_value_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="productbarcode",
            constraint=models.UniqueConstraint(
                condition=Q(is_active=True),
                fields=("barcode",),
                name="uq_barcode_active",
            ),
        ),
    ]
