# Generated by Django 4.2.24 on 2026-02-10 21:39

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_product_active_unique_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='uq_product_name_ci_active',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), condition=models.Q(('is_active', True)), name='uq_product_name_ci_active', violation_error_message='اسم المنتج موجود مسبقاً (بدون حساسية حالة الأحرف).'),
        ),
    ]
