# Generated by Django 4.2.24 on 2026-02-15 00:00

from decimal import Decimal

from django.db import migrations
from django.db.models import F, Q


def normalize_single_unit_conversion_factor(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    Product.objects.filter(
        unit_secondary__isnull=False,
    ).exclude(
        unit_secondary="",
    ).filter(
        unit_secondary=F("unit_primary"),
    ).exclude(
        Q(conversion_factor=Decimal("1"))
    ).update(
        conversion_factor=Decimal("1")
    )


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_remove_product_uq_product_name_ci_active_and_more"),
    ]

    operations = [
        migrations.RunPython(
            normalize_single_unit_conversion_factor,
            migrations.RunPython.noop,
        ),
    ]
