# Generated by Django 4.2.24 on 2026-02-20 23:59

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_global_product_identity_uniqueness'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productcollection',
            name='uq_collection_name_ci',
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_primary',
            field=models.CharField(choices=[('g', 'غرام'), ('pc', 'قطعة'), ('L', 'لتر'), ('PKG', 'طرد'), ('BNDL', 'حزمة')], max_length=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_secondary',
            field=models.CharField(blank=True, choices=[('g', 'غرام'), ('pc', 'قطعة'), ('L', 'لتر'), ('PKG', 'طرد'), ('BNDL', 'حزمة')], max_length=4),
        ),
        migrations.AlterField(
            model_name='productbarcode',
            name='unit_index',
            field=models.IntegerField(choices=[(1, 'Ø§Ù„ÙˆØ\xadØ¯Ø© Ø§Ù„Ø£ÙˆÙ„Ù‰'), (2, 'Ø§Ù„ÙˆØ\xadØ¯Ø© Ø§Ù„Ø«Ø§Ù†ÙŠØ©')]),
        ),
        migrations.AlterField(
            model_name='productunitid',
            name='unit_index',
            field=models.IntegerField(choices=[(1, 'Ø§Ù„ÙˆØ\xadØ¯Ø© Ø§Ù„Ø£ÙˆÙ„Ù‰'), (2, 'Ø§Ù„ÙˆØ\xadØ¯Ø© Ø§Ù„Ø«Ø§Ù†ÙŠØ©')]),
        ),
        migrations.AddConstraint(
            model_name='productcollection',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uq_collection_name_ci', violation_error_message='Ø§Ø³Ù… Ø§Ù„Ù…Ø¬Ù…ÙˆØ¹Ø© Ù…ÙˆØ¬ÙˆØ¯ Ù…Ø³Ø¨Ù‚Ø§Ù‹ (Ø\xadØ³Ø§Ø³ÙŠØ© ØºÙŠØ± Ù…Ù\x81Ø¹Ù„Ø©).'),
        ),
    ]
