# Generated by Django 4.2.24 on 2026-02-26 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_productset_productcollection_hard_delete_flags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
