# Generated by Django 4.2.24 on 2025-12-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '00xx_move_debts_to_debts_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerreturn',
            name='source_bill_serial',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='سيريال فاتورة الشراء الأصلية إن وجد.', null=True),
        ),
    ]
