# Generated by Django 4.2.24 on 2025-10-15 20:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0007_product_stock_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.PositiveIntegerField(db_index=True, editable=False, null=True, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_cost', models.DecimalField(decimal_places=3, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('pay_status', models.CharField(choices=[('paid', 'مدفوعة بالكامل'), ('unpaid', 'غير مدفوعة'), ('partial', 'مدفوعة جزئياً')], default='unpaid', max_length=12)),
                ('paid_amount', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('note', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_index', models.IntegerField(choices=[(1, 'الوحدة الأولى'), (2, 'الوحدة الثانية')], default=1)),
                ('qty_raw', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('qty_u1', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.bill')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='billing.provider'),
        ),
    ]
