# Generated by Django 4.2.24 (manually adjusted) on 2025-10-17 22:20

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
from django.utils import timezone


def backfill_billitem_fields(apps, schema_editor):
    BillItem = apps.get_model('billing', 'BillItem')
    # qty_u1 / qty_raw / total_cost still exist at this point (we remove them AFTER this step)
    qs = BillItem.objects.select_related('bill', 'product').iterator(chunk_size=2000)

    for item in qs:
        changed = False

        # --- qty_primary ---
        if item.qty_primary is None:
            q = None
            # old schema v1: qty_u1 already in PRIMARY units
            if hasattr(item, 'qty_u1') and item.qty_u1 is not None:
                q = item.qty_u1
            # old schema v0: qty_raw in entered unit; convert if secondary
            elif hasattr(item, 'qty_raw') and item.qty_raw is not None:
                q = item.qty_raw
                try:
                    if getattr(item, 'unit_index', 1) == 2:
                        # convert secondary -> primary if product has a factor
                        factor = getattr(item.product, 'conversion_factor', None)
                        if factor:
                            q = Decimal(q) * Decimal(str(factor))
                except Exception:
                    pass
            if q is None:
                q = Decimal('0')
            item.qty_primary = q
            changed = True

        # --- line_total ---
        if item.line_total is None:
            if hasattr(item, 'total_cost') and item.total_cost not in (None, Decimal('0')):
                item.line_total = item.total_cost
            else:
                try:
                    item.line_total = (item.cost or Decimal('0')) * (item.qty_primary or Decimal('0'))
                except Exception:
                    item.line_total = Decimal('0')
            changed = True

        # --- created_at ---
        if item.created_at is None:
            item.created_at = getattr(item.bill, 'created_at', None) or timezone.now()
            changed = True

        if changed:
            item.save(update_fields=['qty_primary', 'line_total', 'created_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_stock_qty'),
        ('billing', '0001_initial'),
    ]

    operations = [
        # Keep model options
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['name']},
        ),

        # Bill changes unrelated to BillItem backfill
        migrations.RenameField(
            model_name='bill',
            old_name='total_cost',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='note',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='pay_status',
        ),

        # IMPORTANT: Do NOT remove old BillItem fields yet. We add new cols first (nullable),
        # backfill them, THEN drop the old cols.

        # New fields on BillItem (TEMP nullable to avoid defaults)
        migrations.AddField(
            model_name='billitem',
            name='created_at',
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='billitem',
            name='line_total',
            field=models.DecimalField(max_digits=14, decimal_places=3, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='billitem',
            name='qty_primary',
            field=models.DecimalField(max_digits=14, decimal_places=3, null=True, blank=True),
        ),

        # Provider extras
        migrations.AddField(
            model_name='provider',
            name='created_at',
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='notes',
            field=models.TextField(blank=True),
        ),

        # Other field alters Django generated (safe to keep)
        migrations.AlterField(
            model_name='bill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='paid_amount',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14,
                                      validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='bill',
            name='serial',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('paid', 'مدفوعة بالكامل'),
                                            ('unpaid', 'غير مدفوعة'),
                                            ('partial', 'مدفوعة جزئياً')],
                                   default='unpaid', max_length=10),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='cost',
            field=models.DecimalField(decimal_places=4, max_digits=12,
                                      validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=12,
                                      validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    related_name='bill_items', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone',
            field=models.CharField(blank=True, max_length=64),
        ),

        # === Backfill the new columns BEFORE dropping old ones ===
        migrations.RunPython(backfill_billitem_fields, migrations.RunPython.noop),

        # Now it’s safe to drop the legacy columns
        migrations.RemoveField(
            model_name='billitem',
            name='qty_raw',
        ),
        migrations.RemoveField(
            model_name='billitem',
            name='qty_u1',
        ),
        migrations.RemoveField(
            model_name='billitem',
            name='total_cost',
        ),

        # Tighten new columns to final constraints
        migrations.AlterField(
            model_name='billitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='line_total',
            field=models.DecimalField(max_digits=14, decimal_places=3),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='qty_primary',
            field=models.DecimalField(max_digits=14, decimal_places=3),
        ),

        # Indexes / constraints
        migrations.AddIndex(
            model_name='billitem',
            index=models.Index(fields=['bill'], name='billing_bil_bill_id_227720_idx'),
        ),
        migrations.AddIndex(
            model_name='billitem',
            index=models.Index(fields=['product'], name='billing_bil_product_555fd3_idx'),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'),
                                              name='uq_provider_name_ci'),
        ),
    ]
