# Generated by Django 4.2.24 on 2025-10-17 22:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_bill_options_alter_provider_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='note',
        ),
        migrations.AlterField(
            model_name='billitem',
            name='line_total',
            field=models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
