# Generated by Django 4.2.24 on 2025-12-21 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_bill_created_by_providerreturn_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
