# Generated by Django 4.2.24 on 2026-01-10 09:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_provider_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='fx_usd_syp',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='settlement_currency',
            field=models.CharField(choices=[('SYP', 'SYP'), ('USD', 'USD')], db_index=True, default='SYP', max_length=3),
        ),
        migrations.AddField(
            model_name='bill',
            name='subtotal_syp',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14),
        ),
        migrations.AddField(
            model_name='bill',
            name='subtotal_usd',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14),
        ),
        migrations.AddField(
            model_name='billitem',
            name='currency',
            field=models.CharField(choices=[('SYP', 'SYP'), ('USD', 'USD')], db_index=True, default='SYP', max_length=3),
        ),
    ]
