# Generated by Django 4.2.24 on 2025-10-18 09:03

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_remove_provider_note_alter_billitem_line_total'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='provider',
            name='uq_provider_name_ci',
        ),
        migrations.AddField(
            model_name='provider',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), condition=models.Q(('is_active', True)), name='uq_provider_name_ci_active'),
        ),
    ]
