# Generated by Django 4.2.24 on 2025-10-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_remove_provider_uq_provider_name_ci_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.CheckConstraint(check=models.Q(('total__gte', 0)), name='bill_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.CheckConstraint(check=models.Q(('paid_amount__gte', 0)), name='bill_paid_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.CheckConstraint(check=models.Q(('paid_amount__lte', models.F('total'))), name='bill_paid_le_total'),
        ),
    ]
