# Generated by Django 4.2.24 on 2025-10-24 08:56

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_productbarcode_unique_together_and_more'),
        ('billing', '0005_bill_bill_total_non_negative_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('total', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('paid', 'مدفوعة بالكامل'), ('unpaid', 'غير مدفوعة'), ('partial', 'مدفوعة جزئياً')], default='unpaid', max_length=10)),
                ('paid_amount', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='billing.provider')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProviderReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_index', models.IntegerField(choices=[(1, 'الوحدة الأولى'), (2, 'الوحدة الثانية')], default=1)),
                ('qty_primary', models.DecimalField(decimal_places=3, max_digits=14)),
                ('cost', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('line_total', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='catalog.product')),
                ('ret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.providerreturn')),
            ],
            options={
                'indexes': [models.Index(fields=['ret'], name='billing_pro_ret_id_e581bb_idx'), models.Index(fields=['product'], name='billing_pro_product_462775_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='providerreturn',
            constraint=models.CheckConstraint(check=models.Q(('total__gte', 0)), name='pret_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='providerreturn',
            constraint=models.CheckConstraint(check=models.Q(('paid_amount__gte', 0)), name='pret_paid_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='providerreturn',
            constraint=models.CheckConstraint(check=models.Q(('paid_amount__lte', models.F('total'))), name='pret_paid_le_total'),
        ),
    ]
