# Generated by Django 4.2.24 on 2025-10-24 21:38

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_providerreturn_providerreturnitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='initial_paid_amount',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='bill',
            name='initial_status',
            field=models.CharField(choices=[('paid', 'مدفوعة بالكامل'), ('unpaid', 'غير مدفوعة'), ('partial', 'مدفوعة جزئياً')], default='unpaid', max_length=10),
        ),
    ]
