# Generated by Django 4.2.24 on 2025-10-25 22:05

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_bill_initial_paid_amount_bill_initial_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditorEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_app', models.CharField(max_length=64)),
                ('source_model', models.CharField(max_length=64)),
                ('source_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('collected', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('closed', 'مغلقة')], default='open', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='CreditorReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(0.001)])),
                ('journal_entry_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DebtorEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_app', models.CharField(max_length=64)),
                ('source_model', models.CharField(max_length=64)),
                ('source_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('paid_amount', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('closed', 'مغلقة')], default='open', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='DebtorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(0.001)])),
                ('journal_entry_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='bill',
            name='bill_paid_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='bill',
            name='bill_paid_le_total',
        ),
        migrations.RemoveConstraint(
            model_name='providerreturn',
            name='pret_paid_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='providerreturn',
            name='pret_paid_le_total',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='initial_paid_amount',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='initial_status',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='status',
        ),
        migrations.RemoveField(
            model_name='providerreturn',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='providerreturn',
            name='status',
        ),
        migrations.AddField(
            model_name='debtorpayment',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.debtorentry'),
        ),
        migrations.AddField(
            model_name='debtorentry',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debtor_entries', to='billing.provider'),
        ),
        migrations.AddField(
            model_name='creditorreceipt',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='billing.creditorentry'),
        ),
        migrations.AddField(
            model_name='creditorentry',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creditor_entries', to='billing.provider'),
        ),
        migrations.AddIndex(
            model_name='debtorpayment',
            index=models.Index(fields=['entry_id'], name='billing_deb_entry_i_3ac800_idx'),
        ),
        migrations.AddIndex(
            model_name='debtorpayment',
            index=models.Index(fields=['created_at'], name='billing_deb_created_1d62b8_idx'),
        ),
        migrations.AddConstraint(
            model_name='debtorpayment',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='debtor_payment_amount_pos'),
        ),
        migrations.AddIndex(
            model_name='debtorentry',
            index=models.Index(fields=['provider_id'], name='billing_deb_provide_7216ac_idx'),
        ),
        migrations.AddIndex(
            model_name='debtorentry',
            index=models.Index(fields=['status'], name='billing_deb_status_79c2be_idx'),
        ),
        migrations.AddIndex(
            model_name='debtorentry',
            index=models.Index(fields=['created_at'], name='billing_deb_created_1f9985_idx'),
        ),
        migrations.AddConstraint(
            model_name='debtorentry',
            constraint=models.UniqueConstraint(fields=('source_app', 'source_model', 'source_id'), name='uniq_debtor_by_source'),
        ),
        migrations.AddConstraint(
            model_name='debtorentry',
            constraint=models.CheckConstraint(check=models.Q(('total__gte', 0)), name='debtor_total_ge0'),
        ),
        migrations.AddConstraint(
            model_name='debtorentry',
            constraint=models.CheckConstraint(check=models.Q(('paid_amount__gte', 0)), name='debtor_paid_ge0'),
        ),
        migrations.AddConstraint(
            model_name='debtorentry',
            constraint=models.CheckConstraint(check=models.Q(('paid_amount__lte', models.F('total'))), name='debtor_paid_le_total'),
        ),
        migrations.AddIndex(
            model_name='creditorreceipt',
            index=models.Index(fields=['entry_id'], name='billing_cre_entry_i_19957c_idx'),
        ),
        migrations.AddIndex(
            model_name='creditorreceipt',
            index=models.Index(fields=['created_at'], name='billing_cre_created_385e8d_idx'),
        ),
        migrations.AddConstraint(
            model_name='creditorreceipt',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='creditor_receipt_amount_pos'),
        ),
        migrations.AddIndex(
            model_name='creditorentry',
            index=models.Index(fields=['provider_id'], name='billing_cre_provide_976a3d_idx'),
        ),
        migrations.AddIndex(
            model_name='creditorentry',
            index=models.Index(fields=['status'], name='billing_cre_status_f1dd1a_idx'),
        ),
        migrations.AddIndex(
            model_name='creditorentry',
            index=models.Index(fields=['created_at'], name='billing_cre_created_b14e45_idx'),
        ),
        migrations.AddConstraint(
            model_name='creditorentry',
            constraint=models.UniqueConstraint(fields=('source_app', 'source_model', 'source_id'), name='uniq_creditor_by_source'),
        ),
        migrations.AddConstraint(
            model_name='creditorentry',
            constraint=models.CheckConstraint(check=models.Q(('total__gte', 0)), name='creditor_total_ge0'),
        ),
        migrations.AddConstraint(
            model_name='creditorentry',
            constraint=models.CheckConstraint(check=models.Q(('collected__gte', 0)), name='creditor_coll_ge0'),
        ),
        migrations.AddConstraint(
            model_name='creditorentry',
            constraint=models.CheckConstraint(check=models.Q(('collected__lte', models.F('total'))), name='creditor_coll_le_total'),
        ),
    ]
