# Generated by Django 4.2.24 on 2025-10-27 10:50

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_creditorentry_creditorreceipt_debtorentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerreturn',
            name='initial_paid',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='providerreturn',
            name='initial_status',
            field=models.CharField(choices=[('paid', 'مدفوعة بالكامل'), ('unpaid', 'غير مدفوعة'), ('partial', 'مدفوعة جزئياً')], default='unpaid', max_length=8),
        ),
    ]
