# Generated by Django 4.2.24 on 2025-10-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_providerreturn_initial_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='serial',
            field=models.PositiveIntegerField(db_index=True, unique=True),
        ),
    ]
