# Generated by Django 4.2.24 on 2025-10-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_alter_bill_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditorentry',
            name='doc_serial',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditorentry',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditorentry',
            name='party_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='creditorentry',
            name='party_type',
            field=models.CharField(choices=[('provider', 'مزود'), ('customer', 'زبون'), ('worker', 'عامل')], default='provider', max_length=16),
        ),
        migrations.AddField(
            model_name='debtorentry',
            name='doc_serial',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debtorentry',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debtorentry',
            name='party_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='debtorentry',
            name='party_type',
            field=models.CharField(choices=[('provider', 'مزود'), ('customer', 'زبون'), ('worker', 'عامل')], default='provider', max_length=16),
        ),
        migrations.AddIndex(
            model_name='creditorentry',
            index=models.Index(fields=['party_name'], name='billing_cre_party_n_ffe4fd_idx'),
        ),
        migrations.AddIndex(
            model_name='debtorentry',
            index=models.Index(fields=['party_name'], name='billing_deb_party_n_878a49_idx'),
        ),
    ]
