# Generated by Django 4.2.24 on 2026-01-11

from django.db import migrations


def forwards(apps, schema_editor):
    Bill = apps.get_model("billing", "Bill")
    for b in Bill.objects.all():
        update_fields = []
        if (b.total_syp is None or b.total_syp == 0) and b.total:
            b.total_syp = b.total
            update_fields.append("total_syp")
        if b.total_usd is None:
            b.total_usd = 0
            update_fields.append("total_usd")
        if b.fx_rate_usd_to_syp_used is None and b.fx_usd_syp is not None:
            b.fx_rate_usd_to_syp_used = b.fx_usd_syp
            update_fields.append("fx_rate_usd_to_syp_used")
        if update_fields:
            b.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0006_bill_fx_rate_usd_to_syp_used_bill_grand_total_syp_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
