# Generated by Django 4.2.24 on 2026-01-12 14:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_backfill_bill_currency_totals'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerreturn',
            name='fx_rate_used',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='providerreturn',
            name='settlement_currency',
            field=models.CharField(choices=[('SYP', 'SYP'), ('USD', 'USD')], db_index=True, default='SYP', max_length=3),
        ),
        migrations.AddField(
            model_name='providerreturn',
            name='total_syp',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14),
        ),
        migrations.AddField(
            model_name='providerreturn',
            name='total_usd',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14),
        ),
        migrations.AddField(
            model_name='providerreturn',
            name='valuation_mode',
            field=models.CharField(choices=[('HISTORICAL', 'Historical FX'), ('CURRENT_FX', 'Current FX')], db_index=True, default='HISTORICAL', max_length=16),
        ),
        migrations.AddField(
            model_name='providerreturnitem',
            name='currency',
            field=models.CharField(choices=[('SYP', 'SYP'), ('USD', 'USD')], db_index=True, default='SYP', max_length=3),
        ),
    ]
