# Generated by Codex on 2026-01-12

from decimal import Decimal
from django.db import migrations


DEC0 = Decimal("0.000")


def backfill_providerreturn_totals(apps, schema_editor):
    ProviderReturn = apps.get_model("billing", "ProviderReturn")

    qs = ProviderReturn.objects.all()
    for pret in qs.iterator():
        total = pret.total or DEC0
        total_syp = getattr(pret, "total_syp", None)
        total_usd = getattr(pret, "total_usd", None)

        if (total_syp is None or total_syp == DEC0) and (total_usd is None or total_usd == DEC0):
            pret.total_syp = total
            pret.total_usd = DEC0
            pret.save(update_fields=["total_syp", "total_usd"])


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0013_providerreturn_fx_rate_used_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_providerreturn_totals, reverse_noop),
    ]
