# Generated by Django 4.2.24 on 2026-01-13 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0012_backfill_moneycontainer_balance_syp'),
        ('billing', '0014_backfill_providerreturn_currency_totals'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='money_container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_bills', to='financials.moneycontainer'),
        ),
    ]
