# Generated by Django 4.2.24 on 2026-03-07

from django.db import migrations


class Migration(migrations.Migration):
    """
    Lineage anchor for billing migrations.

    Historical migration history contains parallel-numbered files and a custom
    bridge migration (`00xx_move_debts_to_debts_app`). This no-op anchor
    establishes a single forward dependency target for future billing schema
    changes.
    """

    dependencies = [
        ("billing", "0017_billitem_snapshot_more"),
    ]

    operations = []
