# Generated by Django 4.2.24 on 2026-03-26

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0018_migration_lineage_anchor"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="creation_paid_syp",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.000"),
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="creation_paid_usd",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.000"),
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="creation_payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "بدون دفع"),
                    ("syp_only", "SYP فقط"),
                    ("usd_only", "USD فقط"),
                    ("separate", "منفصل"),
                    ("mixed", "مختلط"),
                ],
                max_length=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="creation_payment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("paid", "مدفوعة بالكامل"),
                    ("unpaid", "غير مدفوعة"),
                    ("partial", "مدفوعة جزئياً"),
                ],
                db_index=True,
                max_length=10,
                null=True,
            ),
        ),
    ]
