# Generated by Django 4.2.24 on 2026-04-22 10:59

from decimal import Decimal, ROUND_HALF_UP
import django.core.validators
from django.db import migrations, models


TWOPLACES = Decimal("0.01")


def _q2(value):
    if value is None:
        return None
    return Decimal(str(value)).quantize(TWOPLACES, rounding=ROUND_HALF_UP)


def _round_billing_money_fx_fields(apps, schema_editor):
    Bill = apps.get_model("billing", "Bill")
    for obj in Bill.objects.only("id", "fx_rate_usd_to_syp_used").iterator(chunk_size=1000):
        old = obj.fx_rate_usd_to_syp_used
        new = _q2(old)
        if new != old:
            obj.fx_rate_usd_to_syp_used = new
            obj.save(update_fields=["fx_rate_usd_to_syp_used"])

    BillItem = apps.get_model("billing", "BillItem")
    bi_fields = ("cost", "price", "fx_rate_at_txn")
    for obj in BillItem.objects.only("id", *bi_fields).iterator(chunk_size=1000):
        update_fields = []
        for field_name in bi_fields:
            old = getattr(obj, field_name)
            new = _q2(old)
            if new != old:
                setattr(obj, field_name, new)
                update_fields.append(field_name)
        if update_fields:
            obj.save(update_fields=update_fields)

    ProviderReturn = apps.get_model("billing", "ProviderReturn")
    for obj in ProviderReturn.objects.only("id", "fx_rate_used").iterator(chunk_size=1000):
        old = obj.fx_rate_used
        new = _q2(old)
        if new != old:
            obj.fx_rate_used = new
            obj.save(update_fields=["fx_rate_used"])

    ProviderReturnItem = apps.get_model("billing", "ProviderReturnItem")
    pri_fields = ("cost", "fx_rate_at_txn")
    for obj in ProviderReturnItem.objects.only("id", *pri_fields).iterator(chunk_size=1000):
        update_fields = []
        for field_name in pri_fields:
            old = getattr(obj, field_name)
            new = _q2(old)
            if new != old:
                setattr(obj, field_name, new)
                update_fields.append(field_name)
        if update_fields:
            obj.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_public_id_layer'),
    ]

    operations = [
        migrations.RunPython(_round_billing_money_fx_fields, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='bill',
            name='fx_rate_usd_to_syp_used',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='fx_rate_at_txn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='providerreturn',
            name='fx_rate_used',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='providerreturnitem',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='providerreturnitem',
            name='fx_rate_at_txn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
