# Generated by Django 4.2.24 on 2026-04-22 12:03

from decimal import Decimal, ROUND_HALF_UP
import django.core.validators
from django.db import migrations, models


TWOPLACES = Decimal("0.01")


def _q2(value):
    if value is None:
        return None
    return Decimal(str(value)).quantize(TWOPLACES, rounding=ROUND_HALF_UP)


def _round_billing_derived_totals(apps, schema_editor):
    Bill = apps.get_model("billing", "Bill")
    bill_fields = (
        "grand_total_syp",
        "grand_total_usd",
        "subtotal_syp",
        "subtotal_usd",
        "total",
        "total_syp",
        "total_usd",
    )
    for obj in Bill.objects.only("id", *bill_fields).iterator(chunk_size=1000):
        update_fields = []
        for field_name in bill_fields:
            old = getattr(obj, field_name)
            new = _q2(old)
            if new != old:
                setattr(obj, field_name, new)
                update_fields.append(field_name)
        if update_fields:
            obj.save(update_fields=update_fields)

    BillItem = apps.get_model("billing", "BillItem")
    for obj in BillItem.objects.only("id", "line_total").iterator(chunk_size=1000):
        old = obj.line_total
        new = _q2(old)
        if new != old:
            obj.line_total = new
            obj.save(update_fields=["line_total"])

    ProviderReturn = apps.get_model("billing", "ProviderReturn")
    pr_fields = ("total", "total_syp", "total_usd")
    for obj in ProviderReturn.objects.only("id", *pr_fields).iterator(chunk_size=1000):
        update_fields = []
        for field_name in pr_fields:
            old = getattr(obj, field_name)
            new = _q2(old)
            if new != old:
                setattr(obj, field_name, new)
                update_fields.append(field_name)
        if update_fields:
            obj.save(update_fields=update_fields)

    ProviderReturnItem = apps.get_model("billing", "ProviderReturnItem")
    for obj in ProviderReturnItem.objects.only("id", "line_total").iterator(chunk_size=1000):
        old = obj.line_total
        new = _q2(old)
        if new != old:
            obj.line_total = new
            obj.save(update_fields=["line_total"])


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_alter_bill_fx_rate_usd_to_syp_used_and_more'),
    ]

    operations = [
        migrations.RunPython(_round_billing_derived_totals, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='bill',
            name='grand_total_syp',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='bill',
            name='grand_total_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='bill',
            name='subtotal_syp',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='bill',
            name='subtotal_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_syp',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='providerreturn',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='providerreturn',
            name='total_syp',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='providerreturn',
            name='total_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='providerreturnitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
