# Generated by Django 4.2.24 on 2026-05-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0023_alter_bill_creation_paid_syp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerreturn",
            name="request_fingerprint",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
        migrations.AddIndex(
            model_name="providerreturn",
            index=models.Index(fields=["provider", "request_fingerprint", "created_at"], name="billing_pr_reqfp_idx"),
        ),
    ]
