# Generated by Django 4.2.24 on 2026-05-08 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0024_providerreturn_request_fingerprint'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='providerreturn',
            new_name='billing_pro_provide_273707_idx',
            old_name='billing_pr_reqfp_idx',
        ),
    ]
