# Generated by Django 4.2.24 on 2025-11-19 13:57

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0008_alter_productbarcode_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_primary', models.DecimalField(decimal_places=3, help_text='Signed quantity in primary unit (+in, -out).', max_digits=14)),
                ('unit_index', models.IntegerField(choices=[(1, 'الوحدة الأولى'), (2, 'الوحدة الثانية')], default=1, help_text='1 = primary unit, 2 = secondary unit (for info).')),
                ('unit_cost', models.DecimalField(decimal_places=4, help_text='Cost per primary unit at the time of movement.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_cost', models.DecimalField(decimal_places=3, help_text='Absolute value of qty_primary * unit_cost.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('movement_type', models.CharField(choices=[('purchase', 'فاتورة شراء'), ('purchase_reversal', 'عكس فاتورة شراء'), ('provider_return', 'مرتجع إلى المورد'), ('provider_return_reversal', 'عكس مرتجع إلى المورد'), ('sale', 'فاتورة مبيع'), ('sale_return', 'مرتجع من الزبون'), ('adjustment', 'تسوية مخزون')], max_length=32)),
                ('source_app', models.CharField(max_length=32)),
                ('source_model', models.CharField(max_length=64)),
                ('source_id', models.CharField(max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='catalog.product')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['product', 'created_at'], name='inventory_p_product_7e5095_idx'), models.Index(fields=['movement_type'], name='inventory_p_movemen_7b1da5_idx'), models.Index(fields=['source_app', 'source_model', 'source_id'], name='inventory_p_source__2548d0_idx')],
            },
        ),
    ]
