# Generated by Django 4.2.24 on 2025-11-21 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmovement',
            name='container',
            field=models.ForeignKey(blank=True, help_text='Stock container/location affected by this movement.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='stock.productcontainer'),
        ),
        migrations.AddIndex(
            model_name='productmovement',
            index=models.Index(fields=['container', 'product'], name='inventory_p_contain_b959a9_idx'),
        ),
    ]
