# Generated by Django 4.2.24 on 2025-12-15 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_productcontainer_unique_main_store_container'),
        ('inventory', '0002_productmovement_container_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleCostPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_primary', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=3, max_digits=14)),
                ('fifo_layer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.stockfifolayer')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_parts', to='inventory.productmovement')),
            ],
        ),
    ]
