# Generated by Django 4.2.24 on 2025-12-21 19:23

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_salecostpart'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmovement',
            name='origin_source_app',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='productmovement',
            name='origin_source_id',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
        migrations.AddField(
            model_name='productmovement',
            name='origin_source_model',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='salecostpart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salecostpart',
            name='qty_primary',
            field=models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='salecostpart',
            name='total_cost',
            field=models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='salecostpart',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddIndex(
            model_name='productmovement',
            index=models.Index(fields=['origin_source_app', 'origin_source_model', 'origin_source_id'], name='inventory_p_origin__ad78a2_idx'),
        ),
        migrations.AddIndex(
            model_name='salecostpart',
            index=models.Index(fields=['movement'], name='inventory_s_movemen_126554_idx'),
        ),
        migrations.AddIndex(
            model_name='salecostpart',
            index=models.Index(fields=['fifo_layer'], name='inventory_s_fifo_la_b5c4b6_idx'),
        ),
    ]
