# Generated by Django 4.2.24 on 2026-04-22 10:59

from decimal import Decimal, ROUND_HALF_UP
import django.core.validators
from django.db import migrations, models


TWOPLACES = Decimal("0.01")


def _q2(value):
    if value is None:
        return None
    return Decimal(str(value)).quantize(TWOPLACES, rounding=ROUND_HALF_UP)


def _round_inventory_money_fx_fields(apps, schema_editor):
    ProductMovement = apps.get_model("inventory", "ProductMovement")
    pm_fields = (
        "unit_cost",
        "unit_cost_at_txn",
        "sale_unit_price_at_txn",
        "fx_rate_at_txn",
    )
    for obj in ProductMovement.objects.only("id", *pm_fields).iterator(chunk_size=1000):
        update_fields = []
        for field_name in pm_fields:
            old = getattr(obj, field_name)
            new = _q2(old)
            if new != old:
                setattr(obj, field_name, new)
                update_fields.append(field_name)
        if update_fields:
            obj.save(update_fields=update_fields)

    SaleCostPart = apps.get_model("inventory", "SaleCostPart")
    for obj in SaleCostPart.objects.only("id", "unit_cost").iterator(chunk_size=1000):
        old = obj.unit_cost
        new = _q2(old)
        if new != old:
            obj.unit_cost = new
            obj.save(update_fields=["unit_cost"])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_productmovement_snapshots'),
    ]

    operations = [
        migrations.RunPython(_round_inventory_money_fx_fields, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='productmovement',
            name='fx_rate_at_txn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='productmovement',
            name='sale_unit_price_at_txn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='productmovement',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, help_text='Cost per primary unit at the time of movement.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='productmovement',
            name='unit_cost_at_txn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='salecostpart',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
