# Generated by Django 4.2.24 on 2026-04-22 12:03

from decimal import Decimal, ROUND_HALF_UP
import django.core.validators
from django.db import migrations, models


TWOPLACES = Decimal("0.01")


def _q2(value):
    if value is None:
        return None
    return Decimal(str(value)).quantize(TWOPLACES, rounding=ROUND_HALF_UP)


def _round_inventory_derived_totals(apps, schema_editor):
    ProductMovement = apps.get_model("inventory", "ProductMovement")
    pm_fields = ("discount_amount_at_txn", "total_cost")
    for obj in ProductMovement.objects.only("id", *pm_fields).iterator(chunk_size=1000):
        update_fields = []
        for field_name in pm_fields:
            old = getattr(obj, field_name)
            new = _q2(old)
            if new != old:
                setattr(obj, field_name, new)
                update_fields.append(field_name)
        if update_fields:
            obj.save(update_fields=update_fields)

    SaleCostPart = apps.get_model("inventory", "SaleCostPart")
    for obj in SaleCostPart.objects.only("id", "total_cost").iterator(chunk_size=1000):
        old = obj.total_cost
        new = _q2(old)
        if new != old:
            obj.total_cost = new
            obj.save(update_fields=["total_cost"])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_productmovement_fx_rate_at_txn_and_more'),
    ]

    operations = [
        migrations.RunPython(_round_inventory_derived_totals, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='productmovement',
            name='discount_amount_at_txn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='productmovement',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, help_text='Absolute value of qty_primary * unit_cost.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='salecostpart',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
