# Generated by Django 4.2.24 on 2026-01-01 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('provider', 'Provider'), ('customer', 'Customer'), ('staff', 'Staff'), ('system', 'System')], max_length=20)),
                ('name', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financials_counterparty_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('decimals', models.PositiveSmallIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MoneyContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financials_created_containers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(blank=True, max_length=40, unique=True)),
                ('kind', models.CharField(choices=[('cash_add', 'Cash Add'), ('cash_withdraw', 'Cash Withdraw'), ('container_transfer', 'Container Transfer'), ('counterparty_inc', 'Counterparty Increase/Decrease'), ('counterparty_settle', 'Counterparty Settlement'), ('reversal', 'Reversal')], max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('reversed', 'Reversed'), ('void', 'Void')], default='draft', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('source_app', models.CharField(blank=True, max_length=50)),
                ('source_model', models.CharField(blank=True, max_length=80)),
                ('source_id', models.CharField(blank=True, max_length=80)),
                ('group_key', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financials_receipts', to=settings.AUTH_USER_MODEL)),
                ('reverses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='financials.receipt')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PostingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('container', 'Container'), ('counterparty', 'Counterparty')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=18)),
                ('meta_json', models.TextField(blank=True, default='')),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posting_lines', to='financials.moneycontainer')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posting_lines', to='financials.counterparty')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posting_lines', to='financials.currency')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='financials.receipt')),
            ],
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['kind', 'status', 'created_at'], name='financials__kind_2462c6_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['source_app', 'source_model', 'source_id'], name='financials__source__6b50eb_idx'),
        ),
        migrations.AddIndex(
            model_name='postingline',
            index=models.Index(fields=['target_type', 'currency'], name='financials__target__857af0_idx'),
        ),
        migrations.AddIndex(
            model_name='postingline',
            index=models.Index(fields=['container', 'currency'], name='financials__contain_067095_idx'),
        ),
        migrations.AddIndex(
            model_name='postingline',
            index=models.Index(fields=['counterparty', 'currency'], name='financials__counter_1ed6d2_idx'),
        ),
        migrations.AddIndex(
            model_name='postingline',
            index=models.Index(fields=['receipt'], name='financials__receipt_f60820_idx'),
        ),
        migrations.AddConstraint(
            model_name='postingline',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('target_type', 'container'), ('container__isnull', False), ('counterparty__isnull', True)), models.Q(('target_type', 'counterparty'), ('counterparty__isnull', False), ('container__isnull', True)), _connector='OR'), name='financials_postingline_target_matches'),
        ),
        migrations.AddIndex(
            model_name='counterparty',
            index=models.Index(fields=['type', 'name'], name='financials__type_50be50_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='counterparty',
            unique_together={('type', 'name')},
        ),
    ]
