# Generated by Django 4.2.24 on 2026-01-02 18:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("financials", "0001_initial"),
    ]


    operations = [
        migrations.CreateModel(
            name='ContainerFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='moneycontainer',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='financials_allowed_containers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moneycontainer',
            name='currencies',
            field=models.ManyToManyField(related_name='money_containers', to='financials.currency'),
        ),
        migrations.AddField(
            model_name='moneycontainer',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='money_containers', to='financials.containerfeature'),
        ),
    ]
