# Generated by Django 4.2.24 on 2026-01-02 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0004_seed_container_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneycontainer',
            name='currencies',
        ),
        migrations.AddField(
            model_name='moneycontainer',
            name='container_type',
            field=models.CharField(choices=[('drawer', 'Drawer'), ('safe', 'Safe'), ('bank', 'Bank')], db_index=True, default='drawer', max_length=20),
        ),
        migrations.AddField(
            model_name='moneycontainer',
            name='ref_code',
            field=models.CharField(default='MIG-TEMP', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receipt',
            name='kind',
            field=models.CharField(choices=[('opening_balance', 'Opening Balance'), ('cash_add', 'Cash Add'), ('cash_withdraw', 'Cash Withdraw'), ('container_transfer', 'Container Transfer'), ('counterparty_inc', 'Counterparty Increase/Decrease'), ('counterparty_settle', 'Counterparty Settlement'), ('reversal', 'Reversal')], max_length=40),
        ),
        migrations.CreateModel(
            name='MoneyContainerCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_states', to='financials.moneycontainer')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='container_states', to='financials.currency')),
            ],
            options={
                'indexes': [models.Index(fields=['container', 'currency'], name='financials__contain_bc613e_idx'), models.Index(fields=['currency', 'is_enabled'], name='financials__currenc_411a34_idx')],
                'unique_together': {('container', 'currency')},
            },
        ),
    ]
