# Generated by Django 4.2.24 on 2026-01-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0006_backfill_ref_code_and_currency_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneycontainer',
            name='ref_code',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
