# Generated by Django 4.2.24 on 2026-01-02 23:43

from django.db import migrations, models
import financials.models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0008_seed_currencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneycontainer',
            name='ref_code',
            field=models.CharField(db_index=True, default=financials.models.gen_ref_code, max_length=40, unique=True),
        ),
    ]
