# Generated by Django 4.2.24 on 2026-01-08 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financials', '0009_alter_moneycontainer_ref_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='fx_syp_per_usd',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='moneycontainer',
            name='container_type',
            field=models.CharField(choices=[('drawer', 'درج'), ('safe', 'خزنة'), ('bank', 'بنك')], db_index=True, default='drawer', max_length=20),
        ),
        migrations.CreateModel(
            name='FxSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_syp_per_usd', models.DecimalField(decimal_places=6, max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financials_fx_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['is_active', 'updated_at'], name='financials__is_acti_088151_idx')],
            },
        ),
    ]
