# Generated by Django 4.2.24 on 2026-01-11 09:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0010_receipt_fx_syp_per_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneycontainer',
            name='balance_syp',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='moneycontainer',
            name='balance_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
    ]
