# Generated by Django 4.2.24 on 2026-01-11

from django.db import migrations


def forwards(apps, schema_editor):
    MoneyContainer = apps.get_model("financials", "MoneyContainer")
    table = MoneyContainer._meta.db_table

    with schema_editor.connection.cursor() as cursor:
        columns = {
            col.name
            for col in schema_editor.connection.introspection.get_table_description(
                cursor, table
            )
        }

        if "balance" not in columns:
            return

        cursor.execute(
            f"""
            UPDATE {table}
            SET balance_syp = balance
            WHERE balance IS NOT NULL
              AND (balance_syp IS NULL OR balance_syp = 0)
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ("financials", "0011_moneycontainer_balance_syp_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
