# Generated by Django 4.2.24 on 2026-01-13 12:52

from django.db import migrations, models
import django.db.models.deletion
import re


def _backfill_counterparty_links(apps, schema_editor):
    Counterparty = apps.get_model("financials", "Counterparty")
    Provider = apps.get_model("billing", "Provider")
    CustomerProfile = apps.get_model("pos", "CustomerProfile")

    prov_re = re.compile(r"\[provider_id=(\d+)\]")
    cust_re = re.compile(r"\[customer_id=(\d+)\]")

    for cp in Counterparty.objects.all().only("id", "note", "provider_id", "customer_id"):
        note = cp.note or ""
        updates = {}

        if not cp.provider_id:
            m = prov_re.search(note)
            if m:
                pid = int(m.group(1))
                if Provider.objects.filter(pk=pid).exists():
                    updates["provider_id"] = pid

        if not cp.customer_id:
            m = cust_re.search(note)
            if m:
                cid = int(m.group(1))
                if CustomerProfile.objects.filter(pk=cid).exists():
                    updates["customer_id"] = cid

        if updates:
            Counterparty.objects.filter(pk=cp.pk).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_salesbill_fx_rate_used_salesbill_money_container_and_more'),
        ('billing', '0015_bill_money_container'),
        ('financials', '0012_backfill_moneycontainer_balance_syp'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financials_counterparties', to='pos.customerprofile'),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financials_counterparties', to='billing.provider'),
        ),
        migrations.AddIndex(
            model_name='counterparty',
            index=models.Index(fields=['provider'], name='financials__provide_5c62c3_idx'),
        ),
        migrations.AddIndex(
            model_name='counterparty',
            index=models.Index(fields=['customer'], name='financials__custome_ff81e0_idx'),
        ),
        migrations.RunPython(_backfill_counterparty_links, migrations.RunPython.noop),
    ]
