# Generated by Django 4.2.24 on 2026-01-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0013_counterparty_customer_counterparty_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='kind',
            field=models.CharField(choices=[('opening_balance', 'Opening Balance'), ('cash_add', 'Cash Add'), ('cash_withdraw', 'Cash Withdraw'), ('container_transfer', 'Container Transfer'), ('exchange', 'Exchange'), ('counterparty_inc', 'Counterparty Increase/Decrease'), ('counterparty_settle', 'Counterparty Settlement'), ('reversal', 'Reversal')], max_length=40),
        ),
    ]
