# Generated by Django 4.2.24 on 2026-03-08

from django.db import migrations, models
from django.db.models import Count, Q


def _dedupe_linked_counterparties(apps, schema_editor):
    Counterparty = apps.get_model("financials", "Counterparty")
    PostingLine = apps.get_model("financials", "PostingLine")

    def _dedupe_by_fk(*, cp_type: str, fk_field: str) -> None:
        dup_groups = (
            Counterparty.objects.filter(type=cp_type, **{f"{fk_field}__isnull": False})
            .values(fk_field)
            .annotate(c=Count("id"))
            .filter(c__gt=1)
        )
        for group in dup_groups:
            fk_value = group.get(fk_field)
            rows = list(
                Counterparty.objects.filter(type=cp_type, **{fk_field: fk_value}).order_by("id")
            )
            if len(rows) < 2:
                continue
            keep = rows[0]
            duplicate_ids = [r.id for r in rows[1:]]
            if not duplicate_ids:
                continue
            PostingLine.objects.filter(counterparty_id__in=duplicate_ids).update(counterparty_id=keep.id)
            Counterparty.objects.filter(id__in=duplicate_ids).delete()

    _dedupe_by_fk(cp_type="provider", fk_field="provider_id")
    _dedupe_by_fk(cp_type="customer", fk_field="customer_id")


class Migration(migrations.Migration):

    dependencies = [
        ("financials", "0014_alter_receipt_kind"),
    ]

    operations = [
        migrations.RunPython(_dedupe_linked_counterparties, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="counterparty",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="counterparty",
            constraint=models.UniqueConstraint(
                condition=Q(provider__isnull=False),
                fields=("type", "provider"),
                name="fin_cp_uq_type_provider",
            ),
        ),
        migrations.AddConstraint(
            model_name="counterparty",
            constraint=models.UniqueConstraint(
                condition=Q(customer__isnull=False),
                fields=("type", "customer"),
                name="fin_cp_uq_type_customer",
            ),
        ),
        migrations.AddConstraint(
            model_name="counterparty",
            constraint=models.UniqueConstraint(
                condition=Q(customer__isnull=True, provider__isnull=True),
                fields=("type", "name"),
                name="fin_cp_uq_type_name_unlinked",
            ),
        ),
    ]
