# Generated by Django 4.2.24 on 2026-03-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0015_counterparty_identity_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='action_key',
            field=models.CharField(blank=True, max_length=180, null=True, unique=True),
        ),
    ]
