# Generated by Django 4.2.24 on 2026-04-22 10:59

from decimal import Decimal, ROUND_HALF_UP
from django.db import migrations, models


TWOPLACES = Decimal("0.01")


def _q2(value):
    if value is None:
        return None
    return Decimal(str(value)).quantize(TWOPLACES, rounding=ROUND_HALF_UP)


def _round_fxsettings_rate(apps, schema_editor):
    FxSettings = apps.get_model("financials", "FxSettings")
    for obj in FxSettings.objects.only("id", "rate_syp_per_usd").iterator(chunk_size=1000):
        old = obj.rate_syp_per_usd
        new = _q2(old)
        if new != old:
            obj.rate_syp_per_usd = new
            obj.save(update_fields=["rate_syp_per_usd"])


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0016_receipt_action_key'),
    ]

    operations = [
        migrations.RunPython(_round_fxsettings_rate, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='fxsettings',
            name='rate_syp_per_usd',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
    ]
