# Generated by Django 4.2.24 on 2026-05-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0017_alter_fxsettings_rate_syp_per_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postingline',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
    ]
