# Generated by Django 4.2.24 on 2025-11-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['receiver_role'], name='notificatio_receive_310dfd_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['related_app', 'related_model', 'related_id'], name='notificatio_related_b77e92_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['due_date'], name='notificatio_due_dat_e14479_idx'),
        ),
    ]
