# Generated by Django 4.2.24 on 2025-11-01 14:38

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditorDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_app', models.CharField(max_length=64)),
                ('source_model', models.CharField(max_length=64)),
                ('source_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('collected', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('closed', 'مغلقة')], default='open', max_length=8)),
                ('party_type', models.CharField(choices=[('provider', 'مزود'), ('customer', 'زبون'), ('worker', 'عامل')], default='provider', max_length=16)),
                ('party_name', models.CharField(blank=True, max_length=128)),
                ('doc_serial', models.PositiveIntegerField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'billing_creditorentry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CreditorReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=14)),
                ('journal_entry_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'billing_creditorreceipt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DebtorDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_app', models.CharField(max_length=64)),
                ('source_model', models.CharField(max_length=64)),
                ('source_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('closed', 'مغلقة')], default='open', max_length=8)),
                ('party_type', models.CharField(choices=[('provider', 'مزود'), ('customer', 'زبون'), ('worker', 'عامل')], default='provider', max_length=16)),
                ('party_name', models.CharField(blank=True, max_length=128)),
                ('doc_serial', models.PositiveIntegerField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'billing_debtorentry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DebtorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=14)),
                ('journal_entry_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'billing_debtorpayment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DebtReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('debtor', 'مدين'), ('creditor', 'دائن')], max_length=8)),
                ('set_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('creditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='debts.creditordebt')),
                ('debtor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='debts.debtordebt')),
            ],
            options={
                'db_table': 'debts_debtreminder',
                'indexes': [models.Index(fields=['direction'], name='debts_debtr_directi_2755d1_idx'), models.Index(fields=['due_date'], name='debts_debtr_due_dat_57961f_idx')],
            },
        ),
    ]
