# Generated by Django 4.2.24 on 2026-01-13 12:53

from django.db import migrations, models
import django.db.models.deletion
from core.currency import CURRENCY_CHOICES, SYP


def _ensure_db_schema(apps, schema_editor):
    """
    The debts models are unmanaged (db_table lives in billing app),
    so AddField/RemoveConstraint won't touch the DB. We do it manually here.
    """
    def column_names(table):
        with schema_editor.connection.cursor() as cursor:
            return {c.name for c in schema_editor.connection.introspection.get_table_description(cursor, table)}

    def add_col(table, col, sql_type, default_sql=None, nullable=True):
        cols = column_names(table)
        if col in cols:
            return
        if default_sql is None and not nullable:
            raise ValueError(f"default_sql required for NOT NULL column {table}.{col}")
        if default_sql is None:
            schema_editor.execute(f"ALTER TABLE {table} ADD COLUMN {col} {sql_type}")
        else:
            schema_editor.execute(
                f"ALTER TABLE {table} ADD COLUMN {col} {sql_type} DEFAULT {default_sql}{'' if nullable else ' NOT NULL'}"
            )

    # Core tables
    add_col("billing_debtorentry", "currency_code", "varchar(3)", default_sql="'SYP'", nullable=False)
    add_col("billing_debtorentry", "legacy_source_id", "varchar(64)", default_sql="''", nullable=False)
    add_col("billing_debtorentry", "customer_id", "bigint", default_sql=None, nullable=True)

    add_col("billing_creditorentry", "currency_code", "varchar(3)", default_sql="'SYP'", nullable=False)
    add_col("billing_creditorentry", "legacy_source_id", "varchar(64)", default_sql="''", nullable=False)
    add_col("billing_creditorentry", "customer_id", "bigint", default_sql=None, nullable=True)

    # Payments/receipts
    add_col("billing_debtorpayment", "currency_code", "varchar(3)", default_sql="'SYP'", nullable=False)
    add_col("billing_debtorpayment", "receipt_id", "bigint", default_sql=None, nullable=True)
    add_col("billing_debtorpayment", "money_container_id", "bigint", default_sql=None, nullable=True)
    add_col("billing_debtorpayment", "fx_syp_per_usd_used", "numeric(18,6)", default_sql=None, nullable=True)

    add_col("billing_creditorreceipt", "currency_code", "varchar(3)", default_sql="'SYP'", nullable=False)
    add_col("billing_creditorreceipt", "receipt_id", "bigint", default_sql=None, nullable=True)
    add_col("billing_creditorreceipt", "money_container_id", "bigint", default_sql=None, nullable=True)
    add_col("billing_creditorreceipt", "fx_syp_per_usd_used", "numeric(18,6)", default_sql=None, nullable=True)

    # Allow provider_id to be NULL for customer debts (where DB supports it)
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("ALTER TABLE billing_debtorentry ALTER COLUMN provider_id DROP NOT NULL")
        schema_editor.execute("ALTER TABLE billing_creditorentry ALTER COLUMN provider_id DROP NOT NULL")
    elif schema_editor.connection.vendor == "mysql":
        schema_editor.execute("ALTER TABLE billing_debtorentry MODIFY provider_id bigint NULL")
        schema_editor.execute("ALTER TABLE billing_creditorentry MODIFY provider_id bigint NULL")

    # Unique constraints: replace old by new per-currency unique
    vendor = schema_editor.connection.vendor
    if vendor == "postgresql":
        schema_editor.execute("ALTER TABLE billing_debtorentry DROP CONSTRAINT IF EXISTS uniq_debtor_by_source")
        schema_editor.execute("ALTER TABLE billing_creditorentry DROP CONSTRAINT IF EXISTS uniq_creditor_by_source")
        schema_editor.execute(
            "ALTER TABLE billing_debtorentry ADD CONSTRAINT uniq_debtor_by_source_currency UNIQUE (source_app, source_model, source_id, currency_code)"
        )
        schema_editor.execute(
            "ALTER TABLE billing_creditorentry ADD CONSTRAINT uniq_creditor_by_source_currency UNIQUE (source_app, source_model, source_id, currency_code)"
        )
    elif vendor == "sqlite":
        # SQLite cannot drop UNIQUE constraints created in CREATE TABLE.
        # Keep legacy uniqueness; runtime will handle per-currency suffix when needed.
        pass
    else:
        schema_editor.execute("DROP INDEX IF EXISTS uniq_debtor_by_source")
        schema_editor.execute("DROP INDEX IF EXISTS uniq_creditor_by_source")
        schema_editor.execute(
            "CREATE UNIQUE INDEX IF NOT EXISTS uniq_debtor_by_source_currency ON billing_debtorentry (source_app, source_model, source_id, currency_code)"
        )
        schema_editor.execute(
            "CREATE UNIQUE INDEX IF NOT EXISTS uniq_creditor_by_source_currency ON billing_creditorentry (source_app, source_model, source_id, currency_code)"
        )


def _backfill_currency_fields(apps, schema_editor):
    DebtorDebt = apps.get_model("debts", "DebtorDebt")
    CreditorDebt = apps.get_model("debts", "CreditorDebt")

    def normalize_entries(Model):
        for row in Model.objects.all().only("id", "source_id", "currency_code", "legacy_source_id"):
            src = row.source_id or ""
            updates = {}
            if src.endswith(":USD"):
                base = src[:-4]
                if not row.legacy_source_id:
                    updates["legacy_source_id"] = src
                if base:
                    updates["source_id"] = base
                if (row.currency_code or "").upper() != "USD":
                    updates["currency_code"] = "USD"
            else:
                if not row.currency_code:
                    updates["currency_code"] = "SYP"
            if updates:
                Model.objects.filter(pk=row.pk).update(**updates)

    normalize_entries(DebtorDebt)
    normalize_entries(CreditorDebt)

    # Backfill payment/receipt currency using raw SQL (models are unmanaged in migrations).
    schema_editor.execute(
        "UPDATE billing_debtorpayment "
        "SET currency_code = (SELECT currency_code FROM billing_debtorentry WHERE billing_debtorentry.id = billing_debtorpayment.entry_id) "
        "WHERE currency_code IS NULL OR currency_code = ''"
    )
    schema_editor.execute(
        "UPDATE billing_creditorreceipt "
        "SET currency_code = (SELECT currency_code FROM billing_creditorentry WHERE billing_creditorentry.id = billing_creditorreceipt.entry_id) "
        "WHERE currency_code IS NULL OR currency_code = ''"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0001_initial'),
        ('financials', '0013_counterparty_customer_counterparty_provider_and_more'),
        ('pos', '0004_salesbill_fx_rate_used_salesbill_money_container_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtordebt',
            name='currency_code',
            field=models.CharField(choices=CURRENCY_CHOICES, default=SYP, max_length=3),
        ),
        migrations.AddField(
            model_name='debtordebt',
            name='legacy_source_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='debtordebt',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debtor_entries', to='pos.customerprofile'),
        ),
        migrations.AddField(
            model_name='creditordebt',
            name='currency_code',
            field=models.CharField(choices=CURRENCY_CHOICES, default=SYP, max_length=3),
        ),
        migrations.AddField(
            model_name='creditordebt',
            name='legacy_source_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='creditordebt',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creditor_entries', to='pos.customerprofile'),
        ),
        migrations.AddField(
            model_name='debtorpayment',
            name='currency_code',
            field=models.CharField(choices=CURRENCY_CHOICES, default=SYP, max_length=3),
        ),
        migrations.AddField(
            model_name='debtorpayment',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debtor_payments', to='financials.receipt'),
        ),
        migrations.AddField(
            model_name='debtorpayment',
            name='money_container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debtor_payments', to='financials.moneycontainer'),
        ),
        migrations.AddField(
            model_name='debtorpayment',
            name='fx_syp_per_usd_used',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='creditorreceipt',
            name='currency_code',
            field=models.CharField(choices=CURRENCY_CHOICES, default=SYP, max_length=3),
        ),
        migrations.AddField(
            model_name='creditorreceipt',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creditor_receipts', to='financials.receipt'),
        ),
        migrations.AddField(
            model_name='creditorreceipt',
            name='money_container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creditor_receipts', to='financials.moneycontainer'),
        ),
        migrations.AddField(
            model_name='creditorreceipt',
            name='fx_syp_per_usd_used',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.RemoveConstraint(
            model_name='debtordebt',
            name='uniq_debtor_by_source',
        ),
        migrations.RemoveConstraint(
            model_name='creditordebt',
            name='uniq_creditor_by_source',
        ),
        migrations.RunPython(_ensure_db_schema, migrations.RunPython.noop),
        migrations.RunPython(_backfill_currency_fields, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='debtordebt',
            constraint=models.UniqueConstraint(fields=('source_app', 'source_model', 'source_id', 'currency_code'), name='uniq_debtor_by_source_currency'),
        ),
        migrations.AddConstraint(
            model_name='creditordebt',
            constraint=models.UniqueConstraint(fields=('source_app', 'source_model', 'source_id', 'currency_code'), name='uniq_creditor_by_source_currency'),
        ),
    ]
