# Generated by Django 4.2.24 on 2026-01-13 16:42

from django.db import migrations


def _set_debtor_provider_nullable(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("ALTER TABLE billing_debtorentry ALTER COLUMN provider_id DROP NOT NULL")
        return
    if schema_editor.connection.vendor == "mysql":
        schema_editor.execute("ALTER TABLE billing_debtorentry MODIFY provider_id bigint NULL")
        return
    if schema_editor.connection.vendor != "sqlite":
        return

    conn = schema_editor.connection
    with conn.cursor() as cursor:
        cursor.execute(
            "SELECT sql FROM sqlite_master WHERE type='table' AND name='billing_debtorentry'"
        )
        row = cursor.fetchone()
        if not row or not row[0]:
            return
        create_sql = row[0]
        if "provider_id" not in create_sql or "NOT NULL" not in create_sql:
            return

        # Replace NOT NULL on provider_id only.
        new_sql = create_sql.replace("provider_id bigint NOT NULL", "provider_id bigint")
        new_sql = new_sql.replace("provider_id INTEGER NOT NULL", "provider_id INTEGER")
        if new_sql == create_sql:
            return

        cursor.execute("PRAGMA foreign_keys=off")
        cursor.execute("ALTER TABLE billing_debtorentry RENAME TO billing_debtorentry_old")
        cursor.execute(new_sql)

        cursor.execute("PRAGMA table_info(billing_debtorentry_old)")
        cols = [r[1] for r in cursor.fetchall()]
        cols_csv = ", ".join(cols)
        cursor.execute(
            f"INSERT INTO billing_debtorentry ({cols_csv}) SELECT {cols_csv} FROM billing_debtorentry_old"
        )

        cursor.execute("SELECT sql FROM sqlite_master WHERE type='index' AND tbl_name='billing_debtorentry_old' AND sql IS NOT NULL")
        idx_rows = cursor.fetchall()

        cursor.execute("DROP TABLE billing_debtorentry_old")
        for (idx_sql,) in idx_rows:
            cursor.execute(idx_sql.replace("billing_debtorentry_old", "billing_debtorentry"))
        cursor.execute("PRAGMA foreign_keys=on")


class Migration(migrations.Migration):

    dependencies = [
        ("debts", "0002_add_currency_fields"),
    ]

    operations = [
        migrations.RunPython(_set_debtor_provider_nullable, migrations.RunPython.noop),
    ]
