# Generated by Django 4.2.24 on 2026-01-13 17:20

from django.db import migrations


SQL_FORWARD = """
PRAGMA foreign_keys=off;

CREATE TABLE billing_debtorentry_new (
    id integer PRIMARY KEY AUTOINCREMENT,
    source_app varchar(64) NOT NULL,
    source_model varchar(64) NOT NULL,
    source_id varchar(64) NOT NULL,
    created_at datetime NOT NULL,
    total numeric(14,3) NOT NULL DEFAULT '0.000',
    paid_amount numeric(14,3) NOT NULL DEFAULT '0.000',
    status varchar(8) NOT NULL DEFAULT 'open',
    party_type varchar(16) NOT NULL DEFAULT 'provider',
    party_name varchar(128) NOT NULL DEFAULT '',
    doc_serial integer NULL,
    due_date date NULL,
    provider_id bigint NULL,
    currency_code varchar(3) NOT NULL DEFAULT 'SYP',
    legacy_source_id varchar(64) NOT NULL DEFAULT '',
    customer_id bigint NULL,
    CONSTRAINT uniq_debtor_by_source UNIQUE (source_app, source_model, source_id),
    CONSTRAINT debtor_total_ge0 CHECK (total >= 0),
    CONSTRAINT debtor_paid_ge0 CHECK (paid_amount >= 0),
    CONSTRAINT debtor_paid_le_total CHECK (paid_amount <= total),
    FOREIGN KEY(provider_id) REFERENCES billing_provider(id) DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY(customer_id) REFERENCES pos_customerprofile(id) DEFERRABLE INITIALLY DEFERRED
);

INSERT INTO billing_debtorentry_new (
    id, source_app, source_model, source_id, created_at,
    total, paid_amount, status, party_type, party_name,
    doc_serial, due_date, provider_id, currency_code,
    legacy_source_id, customer_id
)
SELECT
    id, source_app, source_model, source_id, created_at,
    total, paid_amount, status, party_type, party_name,
    doc_serial, due_date, provider_id, currency_code,
    legacy_source_id, customer_id
FROM billing_debtorentry;

DROP TABLE billing_debtorentry;
ALTER TABLE billing_debtorentry_new RENAME TO billing_debtorentry;

CREATE INDEX billing_deb_provide_7216ac_idx ON billing_debtorentry (provider_id);
CREATE INDEX billing_deb_status_79c2be_idx ON billing_debtorentry (status);
CREATE INDEX billing_deb_created_1f9985_idx ON billing_debtorentry (created_at);

PRAGMA foreign_keys=on;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("debts", "0003_make_debtor_provider_nullable"),
    ]

    operations = [
        migrations.RunSQL(SQL_FORWARD, reverse_sql=migrations.RunSQL.noop),
    ]
