# Generated by Django 4.2.24 on 2026-03-07

from django.db import migrations


DEBTOR_TABLE_SQL = """
CREATE TABLE "billing_debtorentry" (
    id integer PRIMARY KEY AUTOINCREMENT,
    source_app varchar(64) NOT NULL,
    source_model varchar(64) NOT NULL,
    source_id varchar(64) NOT NULL,
    created_at datetime NOT NULL,
    total numeric(14,3) NOT NULL DEFAULT '0.000',
    paid_amount numeric(14,3) NOT NULL DEFAULT '0.000',
    status varchar(8) NOT NULL DEFAULT 'open',
    party_type varchar(16) NOT NULL DEFAULT 'provider',
    party_name varchar(128) NOT NULL DEFAULT '',
    doc_serial integer NULL,
    due_date date NULL,
    provider_id bigint NULL,
    currency_code varchar(3) NOT NULL DEFAULT 'SYP',
    legacy_source_id varchar(64) NOT NULL DEFAULT '',
    customer_id bigint NULL,
    CONSTRAINT uniq_debtor_by_source_currency UNIQUE (source_app, source_model, source_id, currency_code),
    CONSTRAINT debtor_total_ge0 CHECK (total >= 0),
    CONSTRAINT debtor_paid_ge0 CHECK (paid_amount >= 0),
    CONSTRAINT debtor_paid_le_total CHECK (paid_amount <= total),
    FOREIGN KEY(provider_id) REFERENCES billing_provider(id) DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY(customer_id) REFERENCES pos_customerprofile(id) DEFERRABLE INITIALLY DEFERRED
)
"""


CREDITOR_TABLE_SQL = """
CREATE TABLE "billing_creditorentry" (
    id integer PRIMARY KEY AUTOINCREMENT,
    source_app varchar(64) NOT NULL,
    source_model varchar(64) NOT NULL,
    source_id varchar(64) NOT NULL,
    created_at datetime NOT NULL,
    total numeric(14,3) NOT NULL DEFAULT '0.000',
    collected numeric(14,3) NOT NULL DEFAULT '0.000',
    status varchar(8) NOT NULL DEFAULT 'open',
    provider_id bigint NULL,
    doc_serial integer NULL CHECK (doc_serial >= 0),
    due_date date NULL,
    party_name varchar(128) NOT NULL DEFAULT '',
    party_type varchar(16) NOT NULL DEFAULT 'provider',
    currency_code varchar(3) NOT NULL DEFAULT 'SYP',
    legacy_source_id varchar(64) NOT NULL DEFAULT '',
    customer_id bigint NULL,
    CONSTRAINT uniq_creditor_by_source_currency UNIQUE (source_app, source_model, source_id, currency_code),
    CONSTRAINT creditor_total_ge0 CHECK (total >= 0),
    CONSTRAINT creditor_coll_ge0 CHECK (collected >= 0),
    CONSTRAINT creditor_coll_le_total CHECK (collected <= total),
    FOREIGN KEY(provider_id) REFERENCES billing_provider(id) DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY(customer_id) REFERENCES pos_customerprofile(id) DEFERRABLE INITIALLY DEFERRED
)
"""


def _table_exists(cursor, table_name: str) -> bool:
    cursor.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name=%s",
        [table_name],
    )
    return cursor.fetchone() is not None


def _normalize_source_identity_sqlite(cursor, table_name: str) -> None:
    cursor.execute(
        f"""
        UPDATE "{table_name}"
        SET currency_code = UPPER(currency_code)
        WHERE currency_code IS NOT NULL
        """
    )
    cursor.execute(
        f"""
        UPDATE "{table_name}"
        SET currency_code = 'SYP'
        WHERE currency_code IS NULL OR currency_code = ''
        """
    )
    cursor.execute(
        f"""
        UPDATE "{table_name}"
        SET legacy_source_id = ''
        WHERE legacy_source_id IS NULL
        """
    )
    # Canonicalize legacy source ids like "<id>:USD" when this does not collide
    # with an already canonicalized USD row.
    cursor.execute(
        f"""
        UPDATE "{table_name}"
        SET
            legacy_source_id = CASE
                WHEN COALESCE(legacy_source_id, '') = '' THEN source_id
                ELSE legacy_source_id
            END,
            source_id = SUBSTR(source_id, 1, LENGTH(source_id) - 4),
            currency_code = 'USD'
        WHERE source_id LIKE '%:USD'
          AND LENGTH(source_id) > 4
          AND NOT EXISTS (
              SELECT 1
              FROM "{table_name}" dup
              WHERE dup.id <> "{table_name}".id
                AND dup.source_app = "{table_name}".source_app
                AND dup.source_model = "{table_name}".source_model
                AND dup.source_id = SUBSTR("{table_name}".source_id, 1, LENGTH("{table_name}".source_id) - 4)
                AND UPPER(COALESCE(dup.currency_code, 'SYP')) = 'USD'
          )
        """
    )
    # Keep compatibility trail for rows that still carry a legacy suffix.
    cursor.execute(
        f"""
        UPDATE "{table_name}"
        SET legacy_source_id = source_id
        WHERE source_id LIKE '%:USD'
          AND LENGTH(source_id) > 4
          AND COALESCE(legacy_source_id, '') = ''
        """
    )
    cursor.execute(
        f"""
        UPDATE "{table_name}"
        SET currency_code = 'USD'
        WHERE source_id LIKE '%:USD'
          AND LENGTH(source_id) > 4
          AND UPPER(COALESCE(currency_code, '')) <> 'USD'
        """
    )


def _rebuild_table_sqlite(cursor, table_name: str, create_sql: str) -> None:
    if not _table_exists(cursor, table_name):
        return

    cursor.execute(
        "SELECT sql FROM sqlite_master WHERE type='index' AND tbl_name=%s AND sql IS NOT NULL ORDER BY name",
        [table_name],
    )
    index_sql = [row[0] for row in cursor.fetchall() if row and row[0]]

    cursor.execute(f'PRAGMA table_info("{table_name}")')
    old_columns = [row[1] for row in cursor.fetchall()]

    new_table_name = f"{table_name}_new_0005"
    new_sql = create_sql.replace(
        f'CREATE TABLE "{table_name}"',
        f'CREATE TABLE "{new_table_name}"',
        1,
    )
    cursor.execute(new_sql)

    cursor.execute(f'PRAGMA table_info("{new_table_name}")')
    new_columns = [row[1] for row in cursor.fetchall()]
    common_columns = [col for col in old_columns if col in new_columns]
    columns_csv = ", ".join(f'"{col}"' for col in common_columns)
    cursor.execute(
        f'INSERT INTO "{new_table_name}" ({columns_csv}) SELECT {columns_csv} FROM "{table_name}"'
    )

    cursor.execute(f'DROP TABLE "{table_name}"')
    cursor.execute(f'ALTER TABLE "{new_table_name}" RENAME TO "{table_name}"')
    for idx_sql in index_sql:
        cursor.execute(idx_sql)


def _repair_fk_target(cursor, table_name: str, *, old_ref: str, new_ref: str) -> None:
    if not _table_exists(cursor, table_name):
        return
    cursor.execute(
        "SELECT sql FROM sqlite_master WHERE type='table' AND name=%s",
        [table_name],
    )
    row = cursor.fetchone()
    if not row or not row[0]:
        return
    create_sql = row[0]
    if old_ref not in create_sql:
        return
    fixed_sql = create_sql.replace(old_ref, new_ref)
    _rebuild_table_sqlite(cursor, table_name, fixed_sql)


def _upgrade_schema_and_identity(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor == "postgresql":
        schema_editor.execute("ALTER TABLE billing_debtorentry ALTER COLUMN provider_id DROP NOT NULL")
        schema_editor.execute("ALTER TABLE billing_creditorentry ALTER COLUMN provider_id DROP NOT NULL")
        return
    if vendor == "mysql":
        schema_editor.execute("ALTER TABLE billing_debtorentry MODIFY provider_id bigint NULL")
        schema_editor.execute("ALTER TABLE billing_creditorentry MODIFY provider_id bigint NULL")
        return
    if vendor != "sqlite":
        return

    conn = schema_editor.connection
    with conn.cursor() as cursor:
        cursor.execute("PRAGMA foreign_keys=OFF")
        try:
            _normalize_source_identity_sqlite(cursor, "billing_debtorentry")
            _normalize_source_identity_sqlite(cursor, "billing_creditorentry")

            _rebuild_table_sqlite(cursor, "billing_debtorentry", DEBTOR_TABLE_SQL)
            _rebuild_table_sqlite(cursor, "billing_creditorentry", CREDITOR_TABLE_SQL)
            _repair_fk_target(
                cursor,
                "billing_debtorpayment",
                old_ref='"billing_debtorentry_old_0005"',
                new_ref='"billing_debtorentry"',
            )
            _repair_fk_target(
                cursor,
                "billing_creditorreceipt",
                old_ref='"billing_creditorentry_old_0005"',
                new_ref='"billing_creditorentry"',
            )
        finally:
            cursor.execute("PRAGMA foreign_keys=ON")


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("billing", "0018_migration_lineage_anchor"),
        ("debts", "0004_sqlite_debtorentry_provider_nullable"),
    ]

    operations = [
        migrations.RunPython(_upgrade_schema_and_identity, migrations.RunPython.noop),
    ]
