# Generated by Django 4.2.24 on 2026-04-05 21:12

import debts.models
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0016_receipt_action_key'),
        ('billing', '0019_bill_creation_payment_intent'),
        ('pos', '0008_sales_snapshot_more'),
        ('debts', '0005_sqlite_schema_integrity_and_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=debts.models._debt_public_id_default, editable=False, max_length=24, unique=True)),
                ('direction', models.CharField(choices=[('payable', 'Payable'), ('receivable', 'Receivable')], db_index=True, max_length=12)),
                ('cause_type', models.CharField(choices=[('purchase_bill', 'Purchase Bill'), ('pos_bill', 'POS Bill'), ('provider_return', 'Provider Return'), ('manual', 'Manual Debt')], db_index=True, max_length=32)),
                ('cause_id', models.CharField(db_index=True, max_length=64)),
                ('source_app', models.CharField(blank=True, default='billing', max_length=64)),
                ('other_party_type', models.CharField(choices=[('provider', 'Provider'), ('customer', 'Customer'), ('system_user', 'System User'), ('other', 'Other')], db_index=True, max_length=16)),
                ('other_party_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor_username', models.CharField(blank=True, default='', max_length=150)),
                ('total_syp', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('total_usd', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('remaining_syp', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('remaining_usd', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], db_index=True, default='open', max_length=8)),
                ('note', models.TextField(blank=True, default='')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='central_debts', to='pos.customerprofile')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='central_debts', to='billing.provider')),
            ],
            options={
                'db_table': 'debts_debtrecord',
            },
        ),
        migrations.CreateModel(
            name='DebtSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor_username', models.CharField(blank=True, default='', max_length=150)),
                ('payment_syp', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('payment_usd', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('applied_syp', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('applied_usd', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('fx_syp_per_usd_used', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='debts.debtrecord')),
                ('money_container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debt_settlements', to='financials.moneycontainer')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debt_settlements', to='financials.receipt')),
            ],
            options={
                'db_table': 'debts_debtsettlement',
                'indexes': [models.Index(fields=['debt', 'created_at'], name='debts_debts_debt_id_b4f289_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='debtsettlement',
            constraint=models.CheckConstraint(check=models.Q(('payment_syp__gte', 0)), name='debtsettlement_payment_syp_ge0'),
        ),
        migrations.AddConstraint(
            model_name='debtsettlement',
            constraint=models.CheckConstraint(check=models.Q(('payment_usd__gte', 0)), name='debtsettlement_payment_usd_ge0'),
        ),
        migrations.AddConstraint(
            model_name='debtsettlement',
            constraint=models.CheckConstraint(check=models.Q(('applied_syp__gte', 0)), name='debtsettlement_applied_syp_ge0'),
        ),
        migrations.AddConstraint(
            model_name='debtsettlement',
            constraint=models.CheckConstraint(check=models.Q(('applied_usd__gte', 0)), name='debtsettlement_applied_usd_ge0'),
        ),
        migrations.AddConstraint(
            model_name='debtsettlement',
            constraint=models.CheckConstraint(check=models.Q(('payment_syp__gt', 0), ('payment_usd__gt', 0), _connector='OR'), name='debtsettlement_any_payment_positive'),
        ),
        migrations.AddConstraint(
            model_name='debtsettlement',
            constraint=models.CheckConstraint(check=models.Q(('applied_syp__gt', 0), ('applied_usd__gt', 0), _connector='OR'), name='debtsettlement_any_applied_positive'),
        ),
        migrations.AddIndex(
            model_name='debtrecord',
            index=models.Index(fields=['cause_type', 'cause_id'], name='debts_debtr_cause_t_c4e6ca_idx'),
        ),
        migrations.AddIndex(
            model_name='debtrecord',
            index=models.Index(fields=['provider', 'status'], name='debts_debtr_provide_4be266_idx'),
        ),
        migrations.AddIndex(
            model_name='debtrecord',
            index=models.Index(fields=['customer', 'status'], name='debts_debtr_custome_81a84a_idx'),
        ),
        migrations.AddIndex(
            model_name='debtrecord',
            index=models.Index(fields=['created_at'], name='debts_debtr_created_77a406_idx'),
        ),
        migrations.AddConstraint(
            model_name='debtrecord',
            constraint=models.UniqueConstraint(fields=('direction', 'cause_type', 'cause_id'), name='uniq_debtrecord_direction_cause'),
        ),
        migrations.AddConstraint(
            model_name='debtrecord',
            constraint=models.CheckConstraint(check=models.Q(('total_syp__gte', 0)), name='debtrecord_total_syp_ge0'),
        ),
        migrations.AddConstraint(
            model_name='debtrecord',
            constraint=models.CheckConstraint(check=models.Q(('total_usd__gte', 0)), name='debtrecord_total_usd_ge0'),
        ),
        migrations.AddConstraint(
            model_name='debtrecord',
            constraint=models.CheckConstraint(check=models.Q(('remaining_syp__gte', 0)), name='debtrecord_remaining_syp_ge0'),
        ),
        migrations.AddConstraint(
            model_name='debtrecord',
            constraint=models.CheckConstraint(check=models.Q(('remaining_usd__gte', 0)), name='debtrecord_remaining_usd_ge0'),
        ),
        migrations.AddConstraint(
            model_name='debtrecord',
            constraint=models.CheckConstraint(check=models.Q(('remaining_syp__lte', models.F('total_syp'))), name='debtrecord_remaining_syp_le_total'),
        ),
        migrations.AddConstraint(
            model_name='debtrecord',
            constraint=models.CheckConstraint(check=models.Q(('remaining_usd__lte', models.F('total_usd'))), name='debtrecord_remaining_usd_le_total'),
        ),
    ]
