# Generated by Django 4.2.24 on 2026-04-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0006_debtrecord_debtsettlement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtPublicIdSequence',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('next_value', models.BigIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'debts_debtpublicidsequence',
            },
        ),
    ]
