# Generated by Django 4.2.24 on 2026-04-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debts", "0007_debtpublicidsequence"),
    ]

    operations = [
        migrations.AddField(
            model_name="debtrecord",
            name="fx_syp_per_usd_at_creation",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
    ]
