# Generated by Codex on 2026-05-06

from decimal import Decimal, InvalidOperation, ROUND_HALF_UP

from django.db import migrations, models


DEBTOR_TABLE_SQL_2DP = """
CREATE TABLE "billing_debtorentry" (
    id integer PRIMARY KEY AUTOINCREMENT,
    source_app varchar(64) NOT NULL,
    source_model varchar(64) NOT NULL,
    source_id varchar(64) NOT NULL,
    created_at datetime NOT NULL,
    total numeric(14,2) NOT NULL DEFAULT '0.00',
    paid_amount numeric(14,2) NOT NULL DEFAULT '0.00',
    status varchar(8) NOT NULL DEFAULT 'open',
    party_type varchar(16) NOT NULL DEFAULT 'provider',
    party_name varchar(128) NOT NULL DEFAULT '',
    doc_serial integer NULL,
    due_date date NULL,
    provider_id bigint NULL,
    currency_code varchar(3) NOT NULL DEFAULT 'SYP',
    legacy_source_id varchar(64) NOT NULL DEFAULT '',
    customer_id bigint NULL,
    CONSTRAINT uniq_debtor_by_source_currency UNIQUE (source_app, source_model, source_id, currency_code),
    CONSTRAINT debtor_total_ge0 CHECK (total >= 0),
    CONSTRAINT debtor_paid_ge0 CHECK (paid_amount >= 0),
    CONSTRAINT debtor_paid_le_total CHECK (paid_amount <= total),
    FOREIGN KEY(provider_id) REFERENCES billing_provider(id) DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY(customer_id) REFERENCES pos_customerprofile(id) DEFERRABLE INITIALLY DEFERRED
)
"""


CREDITOR_TABLE_SQL_2DP = """
CREATE TABLE "billing_creditorentry" (
    id integer PRIMARY KEY AUTOINCREMENT,
    source_app varchar(64) NOT NULL,
    source_model varchar(64) NOT NULL,
    source_id varchar(64) NOT NULL,
    created_at datetime NOT NULL,
    total numeric(14,2) NOT NULL DEFAULT '0.00',
    collected numeric(14,2) NOT NULL DEFAULT '0.00',
    status varchar(8) NOT NULL DEFAULT 'open',
    provider_id bigint NULL,
    doc_serial integer NULL CHECK (doc_serial >= 0),
    due_date date NULL,
    party_name varchar(128) NOT NULL DEFAULT '',
    party_type varchar(16) NOT NULL DEFAULT 'provider',
    currency_code varchar(3) NOT NULL DEFAULT 'SYP',
    legacy_source_id varchar(64) NOT NULL DEFAULT '',
    customer_id bigint NULL,
    CONSTRAINT uniq_creditor_by_source_currency UNIQUE (source_app, source_model, source_id, currency_code),
    CONSTRAINT creditor_total_ge0 CHECK (total >= 0),
    CONSTRAINT creditor_coll_ge0 CHECK (collected >= 0),
    CONSTRAINT creditor_coll_le_total CHECK (collected <= total),
    FOREIGN KEY(provider_id) REFERENCES billing_provider(id) DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY(customer_id) REFERENCES pos_customerprofile(id) DEFERRABLE INITIALLY DEFERRED
)
"""


DEBTOR_PAYMENT_TABLE_SQL_2DP = """
CREATE TABLE "billing_debtorpayment" (
    "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
    "created_at" datetime NOT NULL,
    "amount" numeric(14,2) NOT NULL,
    "journal_entry_id" integer NULL,
    "entry_id" bigint NOT NULL REFERENCES "billing_debtorentry" ("id") DEFERRABLE INITIALLY DEFERRED,
    currency_code varchar(3) DEFAULT 'SYP' NOT NULL,
    receipt_id bigint,
    money_container_id bigint,
    fx_syp_per_usd_used numeric(18,6),
    CONSTRAINT "debtor_payment_amount_pos" CHECK ("amount" > '0')
)
"""


CREDITOR_RECEIPT_TABLE_SQL_2DP = """
CREATE TABLE "billing_creditorreceipt" (
    "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
    "created_at" datetime NOT NULL,
    "amount" numeric(14,2) NOT NULL,
    "journal_entry_id" integer NULL,
    "entry_id" bigint NOT NULL REFERENCES "billing_creditorentry" ("id") DEFERRABLE INITIALLY DEFERRED,
    currency_code varchar(3) DEFAULT 'SYP' NOT NULL,
    receipt_id bigint,
    money_container_id bigint,
    fx_syp_per_usd_used numeric(18,6),
    CONSTRAINT "creditor_receipt_amount_pos" CHECK ("amount" > '0')
)
"""


def _to_decimal(value):
    try:
        dec = Decimal(str(value))
    except (InvalidOperation, TypeError, ValueError):
        return None
    if not dec.is_finite():
        return None
    return dec


def _round_money_2dp(value: Decimal) -> Decimal:
    return value.quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)


def _normalize_money_values(apps, schema_editor):
    targets = [
        ("debts", "DebtRecord", ["total_syp", "total_usd", "remaining_syp", "remaining_usd"]),
        ("debts", "DebtSettlement", ["payment_syp", "payment_usd", "applied_syp", "applied_usd"]),
        ("debts", "DebtorDebt", ["total", "paid_amount"]),
        ("debts", "DebtorPayment", ["amount"]),
        ("debts", "CreditorDebt", ["total", "collected"]),
        ("debts", "CreditorReceipt", ["amount"]),
        ("billing", "Bill", ["creation_paid_syp", "creation_paid_usd"]),
        ("billing", "ProviderReturn", ["initial_paid"]),
        ("pos", "SalesBill", ["paid_amount"]),
        ("financials", "PostingLine", ["amount"]),
    ]

    for app_label, model_name, field_names in targets:
        model = apps.get_model(app_label, model_name)
        pk_name = model._meta.pk.name
        for field_name in field_names:
            rows = model.objects.all().values(pk_name, field_name).iterator(chunk_size=500)
            for row in rows:
                raw = row.get(field_name)
                if raw is None:
                    continue
                dec = _to_decimal(raw)
                if dec is None:
                    continue
                if dec.as_tuple().exponent >= -2:
                    continue
                rounded = _round_money_2dp(dec)
                model.objects.filter(**{pk_name: row.get(pk_name)}).update(**{field_name: rounded})


def _table_exists(cursor, table_name: str) -> bool:
    cursor.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name=%s",
        [table_name],
    )
    return cursor.fetchone() is not None


def _rebuild_table_sqlite(cursor, table_name: str, create_sql: str) -> None:
    if not _table_exists(cursor, table_name):
        return

    cursor.execute(
        "SELECT sql FROM sqlite_master WHERE type='index' AND tbl_name=%s AND sql IS NOT NULL ORDER BY name",
        [table_name],
    )
    index_sql = [row[0] for row in cursor.fetchall() if row and row[0]]

    cursor.execute(f'PRAGMA table_info("{table_name}")')
    old_columns = [row[1] for row in cursor.fetchall()]

    new_table_name = f"{table_name}_new_0010"
    new_sql = create_sql.replace(
        f'CREATE TABLE "{table_name}"',
        f'CREATE TABLE "{new_table_name}"',
        1,
    )
    cursor.execute(new_sql)

    cursor.execute(f'PRAGMA table_info("{new_table_name}")')
    new_columns = [row[1] for row in cursor.fetchall()]
    common_columns = [col for col in old_columns if col in new_columns]
    columns_csv = ", ".join(f'"{col}"' for col in common_columns)
    cursor.execute(
        f'INSERT INTO "{new_table_name}" ({columns_csv}) SELECT {columns_csv} FROM "{table_name}"'
    )

    cursor.execute(f'DROP TABLE "{table_name}"')
    cursor.execute(f'ALTER TABLE "{new_table_name}" RENAME TO "{table_name}"')
    for idx_sql in index_sql:
        cursor.execute(idx_sql)


def _upgrade_sqlite_legacy_debt_tables(apps, schema_editor):
    if schema_editor.connection.vendor != "sqlite":
        return
    conn = schema_editor.connection
    with conn.cursor() as cursor:
        cursor.execute("PRAGMA foreign_keys=OFF")
        try:
            _rebuild_table_sqlite(cursor, "billing_debtorentry", DEBTOR_TABLE_SQL_2DP)
            _rebuild_table_sqlite(cursor, "billing_creditorentry", CREDITOR_TABLE_SQL_2DP)
            _rebuild_table_sqlite(cursor, "billing_debtorpayment", DEBTOR_PAYMENT_TABLE_SQL_2DP)
            _rebuild_table_sqlite(cursor, "billing_creditorreceipt", CREDITOR_RECEIPT_TABLE_SQL_2DP)
        finally:
            cursor.execute("PRAGMA foreign_keys=ON")


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("billing", "0023_alter_bill_creation_paid_syp_and_more"),
        ("debts", "0009_alter_debtrecord_remaining_syp_and_more"),
        ("financials", "0018_alter_postingline_amount"),
        ("pos", "0012_alter_salesbill_paid_amount"),
    ]

    operations = [
        migrations.RunPython(_normalize_money_values, migrations.RunPython.noop),
        migrations.RunPython(_upgrade_sqlite_legacy_debt_tables, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="debtordebt",
            name="paid_amount",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
        ),
        migrations.AlterField(
            model_name="debtordebt",
            name="total",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
        ),
        migrations.AlterField(
            model_name="debtorpayment",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name="creditordebt",
            name="collected",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
        ),
        migrations.AlterField(
            model_name="creditordebt",
            name="total",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
        ),
        migrations.AlterField(
            model_name="creditorreceipt",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
