# Generated by Django 4.2.24 on 2026-05-14 09:54

import debts.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financials', '0018_alter_postingline_amount'),
        ('billing', '0025_rename_billing_pr_reqfp_idx_billing_pro_provide_273707_idx'),
        ('debts', '0011_money_2dp_check_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderSettlementAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, default=debts.models._provider_settlement_action_public_id_default, editable=False, max_length=24, unique=True)),
                ('action', models.CharField(choices=[('pay_provider', 'Pay Provider'), ('receive_from_provider', 'Receive From Provider')], db_index=True, max_length=32)),
                ('currency', models.CharField(choices=[('SYP', 'SYP'), ('USD', 'USD')], db_index=True, max_length=3)),
                ('requested_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('eligible_total_remaining', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_applied', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('unallocated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('idempotency_key', models.CharField(max_length=180)),
                ('preview_fingerprint', models.CharField(blank=True, default='', max_length=160)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('committed', 'Committed'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=16)),
                ('diagnostics', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debts_provider_settlement_actions', to=settings.AUTH_USER_MODEL)),
                ('money_container', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_settlement_actions', to='financials.moneycontainer')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_settlement_actions', to='billing.provider')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_settlement_actions', to='financials.receipt')),
                ('reversed_by_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reverses_actions', to='debts.providersettlementaction')),
            ],
            options={
                'db_table': 'debts_providersettlementaction',
            },
        ),
        migrations.CreateModel(
            name='ProviderSettlementAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('debt_source', models.CharField(choices=[('central', 'Central'), ('legacy', 'Legacy')], db_index=True, max_length=16)),
                ('direction', models.CharField(choices=[('payable', 'Payable'), ('receivable', 'Receivable')], db_index=True, max_length=12)),
                ('currency', models.CharField(choices=[('SYP', 'SYP'), ('USD', 'USD')], db_index=True, max_length=3)),
                ('debt_id', models.CharField(blank=True, default='', max_length=64)),
                ('debt_public_id', models.CharField(blank=True, default='', max_length=24)),
                ('cause_type', models.CharField(blank=True, default='', max_length=32)),
                ('source_identity', models.CharField(blank=True, default='', max_length=128)),
                ('before_remaining', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('applied', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('after_remaining', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('would_close', models.BooleanField(default=False)),
                ('closed_after', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='debts.providersettlementaction')),
                ('central_debt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_settlement_allocations', to='debts.debtrecord')),
                ('creditor_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_settlement_allocations', to='debts.creditorreceipt')),
                ('debt_settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_settlement_allocations', to='debts.debtsettlement')),
                ('debtor_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_settlement_allocations', to='debts.debtorpayment')),
                ('legacy_creditor_debt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_settlement_allocations', to='debts.creditordebt')),
                ('legacy_debtor_debt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_settlement_allocations', to='debts.debtordebt')),
            ],
            options={
                'db_table': 'debts_providersettlementallocation',
                'indexes': [models.Index(fields=['action', 'sequence'], name='debts_provi_action__417dde_idx'), models.Index(fields=['debt_source', 'direction', 'currency'], name='debts_provi_debt_so_a740e3_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='providersettlementallocation',
            constraint=models.UniqueConstraint(fields=('action', 'sequence'), name='uniq_psa_alloc_action_sequence'),
        ),
        migrations.AddConstraint(
            model_name='providersettlementallocation',
            constraint=models.CheckConstraint(check=models.Q(('before_remaining__gte', 0)), name='psa_alloc_before_ge0'),
        ),
        migrations.AddConstraint(
            model_name='providersettlementallocation',
            constraint=models.CheckConstraint(check=models.Q(('applied__gte', 0)), name='psa_alloc_applied_ge0'),
        ),
        migrations.AddConstraint(
            model_name='providersettlementallocation',
            constraint=models.CheckConstraint(check=models.Q(('after_remaining__gte', 0)), name='psa_alloc_after_ge0'),
        ),
        migrations.AddConstraint(
            model_name='providersettlementallocation',
            constraint=models.CheckConstraint(check=models.Q(('applied__lte', models.F('before_remaining'))), name='psa_alloc_applied_lte_before'),
        ),
        migrations.AddConstraint(
            model_name='providersettlementallocation',
            constraint=models.CheckConstraint(check=models.Q(('after_remaining', django.db.models.expressions.CombinedExpression(models.F('before_remaining'), '-', models.F('applied')))), name='psa_alloc_after_matches_before_minus_applied'),
        ),
        migrations.AddIndex(
            model_name='providersettlementaction',
            index=models.Index(fields=['provider', 'status', 'created_at'], name='debts_provi_provide_9c0656_idx'),
        ),
        migrations.AddIndex(
            model_name='providersettlementaction',
            index=models.Index(fields=['provider', 'currency', 'created_at'], name='debts_provi_provide_7b3cbb_idx'),
        ),
        migrations.AddConstraint(
            model_name='providersettlementaction',
            constraint=models.UniqueConstraint(fields=('provider', 'idempotency_key'), name='uniq_psa_provider_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='providersettlementaction',
            constraint=models.CheckConstraint(check=models.Q(('requested_amount__gte', 0)), name='psa_requested_amount_ge0'),
        ),
        migrations.AddConstraint(
            model_name='providersettlementaction',
            constraint=models.CheckConstraint(check=models.Q(('eligible_total_remaining__gte', 0)), name='psa_eligible_total_ge0'),
        ),
        migrations.AddConstraint(
            model_name='providersettlementaction',
            constraint=models.CheckConstraint(check=models.Q(('total_applied__gte', 0)), name='psa_total_applied_ge0'),
        ),
        migrations.AddConstraint(
            model_name='providersettlementaction',
            constraint=models.CheckConstraint(check=models.Q(('unallocated_amount__gte', 0)), name='psa_unallocated_amount_ge0'),
        ),
        migrations.AddConstraint(
            model_name='providersettlementaction',
            constraint=models.CheckConstraint(check=models.Q(('total_applied__lte', models.F('requested_amount'))), name='psa_applied_lte_requested'),
        ),
    ]
