# Generated by Django 4.2.24 on 2025-12-18 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('api', 'API'), ('error', 'Error'), ('info', 'Info')], db_index=True, max_length=16)),
                ('target_app', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('target_model', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('target_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('before_json', models.TextField(blank=True, default=None, null=True)),
                ('after_json', models.TextField(blank=True, default=None, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('path', models.CharField(blank=True, default='', max_length=512)),
                ('method', models.CharField(blank=True, default='', max_length=16)),
                ('meta_json', models.TextField(blank=True, default=None, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['target_app', 'target_model', 'target_id'], name='audit_log_a_target__487b13_idx'), models.Index(fields=['actor', 'created_at'], name='audit_log_a_actor_i_28ec85_idx'), models.Index(fields=['action', 'created_at'], name='audit_log_a_action_a31d18_idx')],
            },
        ),
    ]
