# Generated by Django 4.2.24 on 2025-12-18 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit_log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('entrypoint', models.CharField(choices=[('unknown', 'Unknown'), ('pos', 'POS'), ('manager', 'Manager'), ('owner', 'Owner'), ('api', 'API')], db_index=True, default='unknown', max_length=16)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('login_path', models.CharField(blank=True, default='', max_length=512)),
                ('logout_reason', models.CharField(blank=True, default='', max_length=64)),
                ('django_session_key', models.CharField(blank=True, default='', max_length=64)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='auditlog',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='audit_log.auditsession'),
        ),
        migrations.AddIndex(
            model_name='auditsession',
            index=models.Index(fields=['actor', 'started_at'], name='audit_log_a_actor_i_264575_idx'),
        ),
        migrations.AddIndex(
            model_name='auditsession',
            index=models.Index(fields=['entrypoint', 'started_at'], name='audit_log_a_entrypo_4461a7_idx'),
        ),
        migrations.AddIndex(
            model_name='auditsession',
            index=models.Index(fields=['ended_at'], name='audit_log_a_ended_a_392132_idx'),
        ),
    ]
