# Generated by Django 4.2.24 on 2025-12-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0002_auditsession_auditlog_session_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['session', 'created_at'], name='audit_log_a_session_2bea8e_idx'),
        ),
    ]
